#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""generate_links.py — The Remaining Open Links (Vol V): body PDF (ReportLab, Report route).

Cloned from generate_theory.py (Vol IV engine): TocDocTemplate + multiBuild,
FreeSerif English typography, cascade palette, tables/diagram/stats/callouts.
Cover generated separately (HTML/Playwright) and merged via pypdf.
"""
import os, sys, hashlib

SKILL_SCRIPTS = "/home/z/my-project/skills/pdf/scripts"
if SKILL_SCRIPTS not in sys.path:
    sys.path.insert(0, SKILL_SCRIPTS)
sys.path.insert(0, "/home/z/my-project/github_master/scripts")

from pdf import install_font_fallback  # skill helper: auto font fallback in Paragraphs

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                PageBreak, CondPageBreak, KeepTogether, Image, HRFlowable)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from PIL import Image as PILImage

from vol5_content_a import CHAPTERS_A, TABLES, FIGURES
from vol5_content_b import CHAPTERS_B

CHAPTERS = CHAPTERS_A + CHAPTERS_B

# ------------------------------------------------------------------ fonts
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
try:  # static NotoSansSC absent on this host; variable font or Sarasa fallback
    pdfmetrics.registerFont(TTFont("Noto Sans SC", f"{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf"))
    pdfmetrics.registerFont(TTFont("Noto Sans SC Bold", f"{FONT_DIR}/truetype/chinese/NotoSansSC[wght].ttf"))
except Exception:
    pdfmetrics.registerFont(TTFont("Noto Sans SC", f"{FONT_DIR}/truetype/chinese/SarasaMonoSC-Regular.ttf"))
    pdfmetrics.registerFont(TTFont("Noto Sans SC Bold", f"{FONT_DIR}/truetype/chinese/SarasaMonoSC-Bold.ttf"))
pdfmetrics.registerFont(TTFont("SarasaMonoSC", f"{FONT_DIR}/truetype/chinese/SarasaMonoSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))

registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")
registerFontFamily("Noto Sans SC", normal="Noto Sans SC", bold="Noto Sans SC Bold")
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")

install_font_fallback()

# ------------------------------------------------------- cascade palette
# (auto-generated by design_engine.py palette-cascade — do not hand-edit)
PAGE_BG       = colors.HexColor('#f5f5f4')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#ebeae8')
TABLE_STRIPE  = colors.HexColor('#ededeb')
HEADER_FILL   = colors.HexColor('#4e4732')
COVER_BLOCK   = colors.HexColor('#746c56')
BORDER        = colors.HexColor('#c5bfac')
ICON          = colors.HexColor('#a48e4b')
ACCENT        = colors.HexColor('#92761f')
ACCENT_2      = colors.HexColor('#3aa0c2')
TEXT_PRIMARY  = colors.HexColor('#151513')
TEXT_MUTED    = colors.HexColor('#7e7c74')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ---------------------------------------------------------------- layout
MARGIN = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN_THRESHOLD = AVAIL_H * 0.25
MAX_KEEP_HEIGHT = PAGE_H * 0.4

DOC_TITLE = "The Remaining Open Links — The Resolution Programme, Volume V"
OUT_PATH = "/home/z/my-project/github_master/scripts/body_links.pdf"

# ---------------------------------------------------------------- styles
body_style = ParagraphStyle("Body", fontName="FreeSerif", fontSize=10.5, leading=17,
                            alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                            spaceBefore=0, spaceAfter=10)
list_style = ParagraphStyle("ListItem", fontName="FreeSerif", fontSize=10.5, leading=16,
                            alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                            leftIndent=20, firstLineIndent=-20, spaceAfter=7)
h1_style = ParagraphStyle("H1", fontName="FreeSerif", fontSize=22, leading=27,
                          alignment=TA_LEFT, textColor=HEADER_FILL,
                          spaceBefore=0, spaceAfter=4)
caption_style = ParagraphStyle("Caption", fontName="FreeSerif", fontSize=8.5, leading=12,
                               alignment=TA_CENTER, textColor=TEXT_MUTED,
                               spaceBefore=3, spaceAfter=6)
quote_style = ParagraphStyle("Quote", fontName="FreeSerif-Italic", fontSize=11, leading=17.5,
                             alignment=TA_LEFT, textColor=TEXT_PRIMARY)
toc_title_style = ParagraphStyle("TOCTitle", fontName="FreeSerif", fontSize=18, leading=23,
                                 alignment=TA_LEFT, textColor=HEADER_FILL, spaceAfter=14)
toc_l0 = ParagraphStyle("TOCLevel0", fontName="FreeSerif", fontSize=11, leading=20,
                        leftIndent=6, textColor=TEXT_PRIMARY)

def table_header_style(fs):
    return ParagraphStyle(f"TH{fs}", fontName="FreeSerif", fontSize=fs, leading=fs + 3.5,
                          alignment=TA_CENTER, textColor=colors.white)

def table_cell_style(fs):
    return ParagraphStyle(f"TC{fs}", fontName="FreeSerif", fontSize=fs, leading=fs + 3.5,
                          alignment=TA_LEFT, textColor=TEXT_PRIMARY)

stat_style = ParagraphStyle("StatBig", fontName="FreeSerif", fontSize=19, leading=23,
                            alignment=TA_CENTER, textColor=ACCENT)
stat_label_style = ParagraphStyle("StatLabel", fontName="FreeSerif", fontSize=8, leading=11,
                                  alignment=TA_CENTER, textColor=TEXT_MUTED)

# ---------------------------------------------------------------- helpers
def add_heading(text, style, level=0):
    key = "h_" + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def no_dash_breaks(text):
    # bind em-dashes to the preceding word so no line starts with a dash
    return text.replace(" — ", "\u00a0— ")

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def embed_image(path, max_width=None, max_height=None):
    if max_width is None:
        max_width = AVAIL_W
    if max_height is None:
        max_height = 400
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(max_width / ow, max_height / oh, 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)

def build_table(key):
    spec = TABLES[key]
    fs = spec["font"]
    ths, tcs = table_header_style(fs), table_cell_style(fs)
    data = [[Paragraph("<b>%s</b>" % h, ths) for h in spec["header"]]]
    for row in spec["rows"]:
        data.append([Paragraph(no_dash_breaks(c), tcs) for c in row])
    col_widths = [r * AVAIL_W for r in spec["ratios"]]
    assert sum(col_widths) <= AVAIL_W + 0.5, "table %s overflows" % key
    t = Table(data, colWidths=col_widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(("BACKGROUND", (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 == 1 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    return t

def callout(text):
    inner = Paragraph(no_dash_breaks(text), quote_style)
    t = Table([[inner]], colWidths=[AVAIL_W * 0.94], hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("LINEBEFORE", (0, 0), (0, -1), 3, ACCENT),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return t

def stats_row(items):
    cell_w = AVAIL_W / 3.0
    row = [[Paragraph("<b>%s</b>" % val, stat_style),
            Paragraph(label, stat_label_style)] for (val, label) in items]
    t = Table([row], colWidths=[cell_w] * 3, hAlign="CENTER")
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 0.75, ACCENT),
        ("LINEBEFORE", (1, 0), (2, 0), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    return t

def render_block(story, block):
    kind, val = block
    if kind == "p":
        story.append(Paragraph(no_dash_breaks(val), body_style))
    elif kind == "quote":
        story.append(Spacer(1, 8))
        story.append(callout(val))
        story.append(Spacer(1, 14))
    elif kind == "ol":
        for i, item in enumerate(val, 1):
            story.append(Paragraph("%d.  %s" % (i, item), list_style))
        story.append(Spacer(1, 4))
    elif kind == "table":
        story.append(Spacer(1, 16))
        tbl = build_table(val)
        cap = Paragraph(TABLES[val]["caption"], caption_style)
        if len(TABLES[val]["rows"]) <= 8:
            story.extend(safe_keep_together([tbl, cap]))
        else:
            story.append(tbl)
            story.append(Spacer(1, 2))
            story.append(cap)
        story.append(Spacer(1, 14))
    elif kind == "stats":
        story.append(Spacer(1, 10))
        story.append(stats_row(val))
        story.append(Spacer(1, 12))
    elif kind == "figure":
        path, capt = FIGURES[val]
        img = embed_image(path, max_width=AVAIL_W, max_height=400)
        cap = Paragraph(capt, caption_style)
        story.append(Spacer(1, 18))
        story.extend(safe_keep_together([img, Spacer(1, 8), cap]))
        story.append(Spacer(1, 16))

# ------------------------------------------------------------ doc + story
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))

def page_decor(canvas, doc):
    canvas.saveState()
    # header: doc title left + accent rule
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.58 * inch, "THE RESOLUTION PROGRAMME · VOLUME V")
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.66 * inch, PAGE_W - MARGIN, PAGE_H - 0.66 * inch)
    # footer: author left + page number right + light rule
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.46 * inch, "Amin Abaee · The Remaining Open Links — The Enrichment, the Law, and the Benchmark")
    if doc.page >= 2:
        canvas.drawRightString(PAGE_W - MARGIN, 0.46 * inch, str(doc.page))
    canvas.restoreState()

doc = TocDocTemplate(OUT_PATH, pagesize=A4,
                     leftMargin=MARGIN, rightMargin=MARGIN,
                     topMargin=MARGIN, bottomMargin=MARGIN,
                     title=DOC_TITLE, author="Z.ai", creator="Z.ai",
                     subject="The remaining open links of the Resolution Programme, "
                             "attacked in order: BT3's enrichment construction (the "
                             "cost-enriched graded category of interfaces, built), "
                             "BT2's equality (the graded small-gain law, closed on the "
                             "computed class with an exact quadratic gap form), and "
                             "Risk 3 (the RockSample benchmark confrontation).")
doc.onFirstPage = page_decor
doc.onLaterPages = page_decor

story = []

# ---- TOC page (front matter; no visible page number on itself)
toc = TableOfContents()
toc.levelStyles = [toc_l0]
toc.dotsMinLevel = 0
story.append(Paragraph("<b>Contents</b>", toc_title_style))
story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceBefore=0, spaceAfter=12))
story.append(toc)
story.append(PageBreak())

# ---- chapters
for idx, ch in enumerate(CHAPTERS, 1):
    title = "%d  ·  %s" % (idx, ch["title"])
    heading = add_heading(title, h1_style, level=0)
    rule = HRFlowable(width="100%", thickness=1.2, color=ACCENT, spaceBefore=0, spaceAfter=10)
    first = ch["blocks"][0]
    story.append(CondPageBreak(H1_ORPHAN_THRESHOLD))
    story.append(Spacer(1, 14))
    if first[0] == "p":
        story.extend(safe_keep_together([heading, rule, Paragraph(no_dash_breaks(first[1]), body_style)]))
        rest = ch["blocks"][1:]
    else:
        story.extend(safe_keep_together([heading, rule]))
        rest = ch["blocks"]
    for block in rest:
        render_block(story, block)
    story.append(Spacer(1, 6))

doc.multiBuild(story)
print("OK body written:", OUT_PATH)
