# -*- coding: utf-8 -*-
"""np_content_b.py — New Laws, New Theorems, New Physics (Vol III): chapters 8-14."""

CHAPTERS_B = [
{
"title": "Theorem VI — Optic Interlacing and the Multiletter Ladder",
"blocks": [
("p", "THEOREM VI (Optic interlacing). Consider the multiletter problem of the transduction corpus — Theorem 7.11’s conditional equality and Open Problem 7.13’s demand for an intrinsic characterization. Then: (i) PROVED-HERE, zero slice — under independent block lifting, the realization ladder multiplies: rank(H<sub>1</sub> ⊗ H<sub>2</sub>) = rank(H<sub>1</sub>)·rank(H<sub>2</sub>), and the determination index is multiplicative under the corresponding direct-product composition, by the Myhill–Nerode characterization of the product automaton; consequently the zero threshold of the composite at block budget M<sub>1</sub>M<sub>2</sub> is exactly the product of the per-block thresholds, and the corpus’s zero-slice law (rank(H) ≤ M) transports intact. (ii) PROVED-HERE, positive slice — the singular values of the tensor lift are exactly the pairwise products {σ<sub>i</sub>(H<sub>1</sub>)σ<sub>j</sub>(H<sub>2</sub>)}, so the unrestricted grounded gap of the composite at any budget is the corresponding order statistic of the product multiset: the multiletter ladder is the product ladder, and the per-letter AAK identity (Theorem 7.9, Δ = σ<sub>M+1</sub>) transfers through it to the composite. (iii) DERIVED, the discharge — Theorem 7.11’s hypothesis, a structure-preserving embedding carrying an AAK-type theorem, is satisfied for independent blocks by the tensor embedding itself, with the approximant class read as the tensor of the per-letter structured classes; the conditional equality therefore holds there. (iv) CONJECTURE, optic-Nehari — for correlated letters, where the optic composite is not a pure tensor, the best structured approximant of a composite is the optic composite of best approximants; this is precisely the missing lemma of Continuation A, and the intercept leakage of Theorem I is what blocks its naive extension, because the correlated composite’s hom-dimension need not factor."),
("p", "The status change this effects on the corpus’s own open problem is the theorem’s substance, and it is worth stating exactly, because the corpus is scrupulous about its own conditionals. Theorem 7.11 assumes a unitary embedding of the multiletter Hankel into a free-semigroup or vector-valued Hardy class that carries a finite-rank approximation theorem — a hypothesis the corpus itself flags as strong and not known to be checkable in general, remarking that only the Eckart–Young–Mirsky lower bound is unconditional. Parts (i)–(ii) discharge that hypothesis for the independent-block case: the tensor product is the embedding, and the product-spectrum law is the approximation theorem on it — both elementary, both exact, neither previously assembled in the corpus’s language. Open Problem 7.13, one undifferentiated demand for an intrinsic characterization, becomes a dichotomy: multiplicativity where the letters are independent — now proved — and optic-Nehari where they are not — now isolated as a named lemma with a precise statement. Reducing an open problem to a named missing lemma is the standard shape of progress in this corpus, and it is the shape delivered here."),
("p", "The connection to Volume II is the reason this theorem carries the continuation’s name. Volume II stated Continuation A as a proof strategy: block-length lifting is tensoring, tensoring is optic composition, so the multiletter ladder is the graded category’s tensor ladder in disguise — and conjectured that the multiletter rung and the graded-trace small-gain law are one missing law in two dialects. Theorem VI makes the first half of that identification literal: the tensor ladder is now proved to carry the multiletter zero slice and positive slice for independent blocks, so whatever law closes the correlated case will be a statement about optic composites that are not tensors — exactly the class where the enrichment, the intercept, and the small-gain equality all live. Honesty compels two notes. First, the discharge in (iii) is partly definitional: choosing the structured class on the composite as the tensor of structured classes is a choice, and the intrinsic question — what the corpus’s Remark 7.18 guards, that no Hardy-space embedding is assumed by default — remains open beneath it. Second, the independent-block case is the easy half, and it must not be advertised as the multiletter theorem; what it buys is a smaller, sharper target, and smaller sharper targets are how this programme has always moved."),
]},
{
"title": "The New Physics",
"blocks": [
("p", "Four claims constitute the new physics, and the first is the headline. Record phase transitions (Theorem IV): the Born records of monitored quantum circuits carry a phase structure — a ladder of non-analytic points of the replica free energies, at p<sub>c</sub><super>(2)</super> = 0.233810 and its higher-replica successors — at which the record statistics’ second-order response concentrates with the same inverse-gap signature that metabolic regulation shows at active-set boundaries. The physics is new on two axes at once: no phase structure in measurement records of monitored circuits is established anywhere in the literature the corpus surveyed, and the quantitative identity of the two response laws — a classical LP substrate and a quantum replica substrate — is a unification claim that only the corpus’s two halves together could even state. It is also certifiable physics: the boundaries are computed by an exact closure whose anchors reproduce to 10<super>−14</super>, so the prediction can be checked without new theory, on production runs the corpus already maintains, and the v23 L = 8 rung currently computing is the natural first scan."),
("p", "Second, obstruction as a physical observable (Theorem V): the intercept dimension, previously a negative theorem, becomes a measurable quantity with an exact calibration — the obstruction index, quantized by dimension combinatorics (4/3 at n = 2r+3, at the qutrit, at the classical boundary), with an operational readout in discrimination success and a hardware protocol attached. Third, the one-wall hypothesis (Law 3’s core): the combinatorial wall and the analytic wall are two faces of one compactness phenomenon. The evidence is structural: the Eckart–Young–Mirsky and AAK floors are compactness statements about the approximant family; weak König’s lemma is the failure of uniform compact search; the Borsuk–Ulam bound converts compactness into a diameter floor; the Weihrauch spectrum — with the halting-stage game’s obstruction sitting exactly at the PA degrees, and recursive capability complete for Σ<super>3</super> — grades the search costs. The reading this suggests for the halting-physics corpus is the genuinely new sentence: the physics of halting is the thermodynamics of compact search, with the PA-degree spectrum playing the role of a temperature scale. Fourth, the curvature–regulation correspondence as cross-domain physics: one quantitative law — second-order concentration at the non-analytic set, magnitude inverse to the gap — now instantiated on metabolic networks, monitored circuits, and governance delay dynamics, with the artefact discriminator as its practical test."),
("stats", [("4/3", "the qutrit obstruction index — exact"), ("0.233810", "the first record-phase boundary — certifiable"), ("0.361", "the E. coli cascade relaxation rate — per cycle")]),
("p", "The discipline that keeps these four honest is the same one the corpus practices on itself, applied at the level of claims rather than proofs. Record phase transitions are a theorem in the two-level fragment and a prediction in general, and the prediction carries its own finite-size check — the L-ladder distinguishes genuine kinks from finite-L smoothing, exactly as the corpus’s finite-size scaling separated the quenched critical point 0.1597(8) from the annealed chain. The observable-obstruction claim is derived, but its hardware test is a genuine experiment, and its failure mode is informative either way: a qutrit reading off 4/3 confirms the tomography and the theory together; anything else localizes the defect in one of them. The one-wall hypothesis is the only claim of the four with no proof face at all — it is the volume’s one piece of pure programme physics, the compactness identification stated so that someone can refute it by exhibiting a compactness modulus that does not control a spectral tail, or prove it by exchanging one for the other. It is listed as such, and it closes this chapter the way the third law closes the ladder: unreachable, priced, and exact about both."),
]},
{
"title": "The New Capabilities",
"blocks": [
("p", "Capability one: certified large-deviation telemetry for monitored quantum circuits. The exact closure turns the ESS law — ESS/B = exp[−2Lt·(Λ(2)−2Λ(1))] — from a warning into an engineering budget curve: at p = 0.16 the exponent is 0.0340 nats per site at L = 8, and the true ESS fractions are 2.7 × 10<super>−8</super>, 3.6 × 10<super>−18</super>, 4.2 × 10<super>−32</super> at L = 8, 12, 16, so any fixed sampling budget fails at a computable system size, and the computation is exact. The self-averaging criterion — the per-site variance of the record count, 0.104–0.106, L-independent — is the sampling certificate that says when a single disorder realization speaks for the ensemble; the record-entropy density ladder (0.1448 to 0.1489 bits per site) is the telemetry channel itself. The protocol: run the monitor, report the record exponents with exact-arithmetic certificates attached, flag the record-phase boundaries by the certified p-locations. This is the first capability in the quantum corpus that an experimentalist could operate without reading the theory, because every number it reports is either exact or carries its own error contract."),
("p", "Capability two: the obstruction spectrometer (Theorem V’s protocol, with its calibration table). Capability three: curvature-guided intervention design. The design rule falls directly out of Theorem IV’s proved metabolic half: interventions placed at curvature atoms — the non-analytic boundaries where second-order response concentrates — buy maximal response per unit cost, because the value–flux coupling identity fixes the exact exchange rate there, and the epistasis structure (ρ<sub>S</sub> = 0.865 between curvature epistasis and footprint overlap) supplies the interaction bookkeeping. The sustainability corpus supplies the calibrated instances: the COD intervention analysis returns a largest robust constant catch of 91.6 kt and a certified-kernel horizon of seven years at the limit reference point; the Edwards analysis returns a smallest securing cut of 7.2 percent against a 618-ft threshold; and — the negative instance that proves the rule — the reactive rules that are “invisible to the kernels of their own triggers” are interventions placed off the concentration set, failing silently exactly where the curvature is not. The frozen-protocol forecast ladders are the falsification harness, and Prediction 9 states the dominance test."),
("p", "Capability four: dual-certified policy bands — machine-checkable governance. The minimax dual certificate theorem says the common safe-action set is empty precisely when an adversarial probability measure on the boundary–disturbance bundle drives expected inward drift negative against every control, with support of at most k+1 points, tight; the computational certification bridge turns it into a finite linear program whose optimum brackets the continuous-time safety value from both sides with certified error inflation. Assembled, these are policy proofs: a policy certificate is a small rational object — a measure with at most k+1 atoms, an exact margin (the benchmark instance certifies obstruction at Y = 6 with margin 3/50 on the two-stock problem whose critical aggregate is exactly 27/5) — that any third party can verify without re-solving anything, in the exact arithmetic the corpus already practices. This is the sustainability corpus’s answer to its own reception risk: not more models, but certificates that travel. Capability five, stated briefly because the chess paper already carries it: role-decomposed theory engines. The CSR sufficiency theorem and the amplification bound P ≥ [θ(1−(1−q)<super>w</super>)]<super>L</super> are substrate-independent; the corpus’s own arena agents are running instances; and the society architecture — generator, critics, verifier, attacker, coordinator — is the operational form of this volume’s own discipline of separating the proved from the conjectured."),
]},
{
"title": "The Falsification Table",
"blocks": [
("p", "A claim to new science is a contract with its refuters, and this volume signs nine. The table states each prediction with its experiment, its observable, its predicted value, and the verdict that would count — the same contract format the corpus’s own claims-evidence maps practice, extended from claims to creations. Three of the nine run on data that already exists (the E. coli panels, the delay-dynamics models, the ECOMOD branch), four run on instruments the corpus already maintains (the monitored-circuit production runs, the intervention models, the belief-state exact-arithmetic engines), and two require new hardware or new simulation (the spectrometer readings, the arrow-of-time families). None of them requires new theory to check, which is deliberate: a prediction that cannot be tested without first proving something is not a prediction but a promissory note, and the corpus has always refused those."),
("table", "falsify"),
("p", "The verdict conditions are asymmetric by design, because the claims are asymmetric. Predictions 2, 4, and 5 test exact values, so they measure the apparatus as much as the theory — a kink that fails to localize inside the certified window, or a qutrit ladder that misses 4/3, falsifies cleanly. Predictions 1, 3, and 9 test scaling laws, so they carry confidence intervals rather than equalities — the 0.361 slope within bounds, the 3/2 exponent inside its bootstrap interval on new substrates. Predictions 6, 7, and 8 test the conjectural and diagnostic faces, and they are refuted by single counterexamples or single classification failures: one family with obstruction and zero entropy production kills the Resolution Second Law; one equilibrium observer that detects its own bottleneck kills Law 0; one crossing class the discriminator cannot separate kills the authentication capability. The asymmetry is the honesty register made operational: the further a claim sits from proof, the easier the volume has made it to kill."),
]},
{
"title": "The Provenance Ledger",
"blocks": [
("p", "The ledger closes the loop the mandate opened. Every new claim in this volume — four laws, six theorems, four physics claims, five capabilities — is listed against its corpus sources, cited by label and version, with the novelty delta stated in the third column as a countable difference: what was added, and of what kind. The ledger is the volume’s answer to the question DeepSeek put to the entire programme, and that Volume II put to Volume I: does the unified framework prove something new? The answer given here is not a yes but an inventory — new statements, discharged hypotheses, assembled invariants, unmeasured numbers, unbuilt instruments — because an inventory can be audited and a yes cannot. An auditor with access to the twelve repositories can verify every row: the sources exist, the labels resolve, the deltas are differences between what the rows say and what the sources say."),
("table", "provenance"),
("p", "Two patterns in the ledger are worth reading off, because they describe the shape of the volume’s contribution better than any summary sentence. First, no row has an empty source column: nothing here is free-floating — every creation is grounded in proved mathematics that was already sitting in the corpus, which is exactly what distinguishes this constructive turn from the juxtaposition risk the whole programme has been warned against since DeepSeek’s first ruling. Second, no row has an empty delta column either: nothing here is a restatement — every row adds a statement, a discharge, an invariant, a number, or a protocol that the source manuscripts do not contain. Grounded novelty, row by row, is the strongest form of “new” that honest synthesis can deliver, and the ledger is its proof of work."),
]},
{
"title": "The Honesty Register",
"blocks": [
("p", "The strongest attacks on each new object, stated as an adversary would state them. Against Law 0: an equilibrium observer might detect its bottleneck through a channel the reversibility criterion does not cover — a driven-but-sufficient source with positive entropy production and zero obstruction would leave the law standing but gut its converse; the simulation search of Prediction 7 is where this is settled. Against Theorem I: the conservation form is assembled from proved transport propositions, but the functorial statement — the one that would make “conserved” precise in the graded category — is blocked on the enrichment that Volume II named and this volume does not build; until then, the first law is a family of instances with a common bookkeeping, not yet one theorem. Against Theorem II: the equality analysis is proved only in the isometry case, and the pairing of the 0.361 relaxation with the 3/2 fatigue is a reading, not a derivation — the two laws govern the same loop in different regimes, but no lemma here derives one from the other."),
("p", "Against Theorem III: parts (a)–(c) are standard mathematics applied to corpus objects, and their novelty is the assembly; part (d3) is a conjecture whose witnesses are correlational — the metabolic arrow, the fatigue exponent, the replica gap, the ECOMOD window, and the record rate function all point the same way, but none of them entails the implication, and a lumpable but driven counterexample family is a live possibility. Against Theorem IV: the kink prediction could be smoothed by finite-L effects rather than refuted by them, which is why the prediction includes the L-ladder as its own control; the metabolic half is proved, the quantum half is proved only at the level of eigenvalue-crossing perturbation in the fragment, and the cross-substrate identity of the two response laws is an extrapolation with two data points. Against Theorem V: the meter presumes the affine model of the instrument family, and a hardware deviation measures the tomography before it measures the theory. Against Theorem VI: the independent-block discharge is the easy half, partly definitional, and must not be read as the multiletter theorem; against the one-wall hypothesis: it has no proof face, and it is stated so that its refutation is a well-defined task. None of the six theorems claims its open core; the cores are in Table 2."),
("p", "What this volume does not claim, finally, because the programme’s credibility rests on these denials holding. It does not claim BT1a — the obstruction-to-Hankel recovery remains the deepest open link, untouched here. It does not claim the cost-enriched graded category exists — it remains the load-bearing gap, and two of the six theorems (I and VI) would upgrade from assemblies to single functorial statements the day it is built. It does not claim any cohomological, homotopical, or higher-arity completeness for the obstruction datum — the monograph’s own scope guard stands, and DeepSeek’s Bridge Theorem 1 remains corrected, not vindicated. It does not claim the multiletter AAK theorem, the arrow-of-time theorem, or the graded small-gain equality — it claims discharged fragments, named lemmas, and falsifiable conjectures in their direction. And it does not claim that any prediction has been tested: the nine entries of Table 3 are offers, not results. The volume creates at the frontier; the frontier moves; the ledger records where it stopped."),
]},
{
"title": "Research Orders",
"blocks": [
("p", "The priority queue is ordered by information per unit cost, and the first three orders are cheap because the apparatus already exists. Order one: run the record-phase scan. The monitored circuits are solved, the closure is exact, the boundaries are certified at 0.233810 and above, the production cells at p = 0.16 sit a step above the quenched critical point, and the v23 L = 8 rung is computing now — a p-scan across the annealed chain with the exact exponent ladder attached is the fastest falsification or confirmation of this volume’s headline physics. Order two: the E. coli cycle-size scan — a new statistic (approach-to-asymptote against 1 − 0.697<super>k</super>) on panels that already exist. Order three: state and attack optic-Nehari for correlated composites — a named lemma with a precise statement, the one proof that would upgrade a published conditional theorem (7.11) and split a published open problem (7.13) permanently; it is the highest-value proof target in the queue because Volume II’s Continuation A and the graded-trace small-gain law both converge on it."),
("p", "Orders four through seven are the build-and-prove tier. Four: write the obstruction-spectrometer protocol as a short instrument paper — every formula is proved in the instruments corpus, the calibration table is exact, and the qutrit prediction is a clean experimental contract. Five: the arrow-of-time simulation campaign of Prediction 6, which either kills part (d3) cheaply or arms the theorem that Continuation B was pointing at. Six: the enrichment — unchanged in priority from Volume II, still the load-bearing gap, and now carrying two upgrade promises (Theorems I and VI) instead of one. Seven: BT1a, the deep identification, last as ever. The staging respects DeepSeek’s path with the same correction Volume II made: the bridge paper first, fifteen to twenty pages, but its skeleton now has meat that the earlier volumes could not give it — a proved fragment of Continuation A, a realized finite-case of Continuation B, a conservation law with instances across eight domains, and a physics prediction that a running computation can check this month."),
("quote", "If you can prove even one, you have a major contribution. If you can prove all three, you have a unified theory of viability, information, and composition."),
("p", "That was DeepSeek’s closing verdict on the programme, and this volume answers it in the only currency that verdict accepts. Six theorems are stated, each with its proved halves separated from its open core; two discharged fragments advance the two continuations it offered; four laws legislate the no-go theorems it wanted unified; nine predictions stand ready for their refuters; five instruments wait for their operators. The corpus’s own epistemology — charts carry certificates, ladders carry monotonicity, limits carry invariants — predicts what these creations are: the invariants the limit was carrying all along. The climb that Volume II ended by recommending continues here with handholds it did not have: the ladder is the same, but three more rungs hold weight, and the next one is named."),
]},
]
