# -*- coding: utf-8 -*-
"""rp_content_a.py — The Resolution Programme: chapters 1-7 (content module)."""

FIGURE_DIAGRAM = "/home/z/my-project/scripts/diagram_resolution.png"

TABLES = {
    "disguises": {
        "caption": "Table 1 — The one constraint, heard in nine dialects",
        "header": ["The interface acting as the “sensor”", "The constraint’s name", "Where it lives in the corpus"],
        "ratios": [0.30, 0.30, 0.40],
        "font": 9.0,
        "rows": [
            ["Physical sensors", "Partial observability; information sets", "ECD Vol 1–2; the mechanics front end"],
            ["Prefix of the history", "Causality", "ECD causal histories; sequential transducers"],
            ["The agent’s internal state", "Finite memory (Myhill–Nerode)", "The bounded-transduction corpus"],
            ["One party’s own input", "Bell locality", "ECD Bell module; CHSH"],
            ["Finite-precision views of the input", "Continuity; Weihrauch computability", "ECD computability interface"],
            ["The process interface itself", "No-currying; the intercept principle", "Quantum combs; environmental currying"],
            ["The next-token vocabulary", "Autoregressive myopia", "The chess-LLM society"],
            ["The aggregation grid", "Composition concealment", "ECOMOD biocapacity drawdown"],
            ["The sampling regime", "Sampled governance", "Sustainability paper 5 (v47)"],
        ],
    },
    "prices": {
        "caption": "Table 2 — The price schedule: measured prices and their certificates",
        "header": ["Bottleneck", "The measured price", "Certificate"],
        "ratios": [0.26, 0.42, 0.32],
        "font": 9.0,
        "rows": [
            ["Absent-minded driver, 0 bits", "Deterministic value 1; behavioural 4/3 (maximum of 4p − 3p<super>2</super>)", "Two-world fibre conflict; a single landmark is a size-1 repair"],
            ["Absent-minded driver, 1 bit", "Value 4", "Achievability: split the fibre"],
            ["CHSH, 0 bits of communication", "Win probability at most 3/4", "CHSH inequality as a Farkas vector"],
            ["CHSH, 1 bit", "Win probability 1", "One-bit protocol"],
            ["Quantum instruments", "In-radius 2/(n d<sub>B</sub> min{d<sub>A</sub>, d<sub>B</sub>}); qutrit flat-width exactly 4/3", "Complete flat-width classification"],
            ["Uniform mass–spring chain", "(K<super>−1</super>)<sub>ij</sub> = min(i,j)/k: no decay, maximal combinatorial width; every past–future block rank 1", "Rank identity; two scalars per cut"],
            ["Monitored circuits, L = 8/12/16", "Λ(2) = −0.1219 / −0.1239 / −0.1245 (exact)", "Z3 two-sided certificates"],
            ["Born-record ESS exponent", "0.0340 / 0.0349 / 0.0353 (corrected)", "Exact-arithmetic closure suite"],
            ["E. coli transcription layer", "r = +0.395 (424 genes); protein-layer null r = −0.083", "Empirical differential test"],
            ["Viability fixed point", "Contraction constant 0.697; fatigue exponent 3/2", "Seven-optic Banach iteration"],
        ],
    },
    "map": {
        "caption": "Table 3 — The corpus map: every work docked into the programme",
        "header": ["Corpus line", "The bottleneck", "Slot in the programme", "Signature results"],
        "ratios": [0.21, 0.19, 0.24, 0.36],
        "font": 8.3,
        "rows": [
            ["Effective Causal Descent, Vol 1 (v47)", "Sensor quotient: worlds to observations", "Qualitative core: the constraint and its disguises; diagnostics; morphisms", "Obstruction datum; selector kernel; prediction games; Bell module; Weihrauch/DNR interface"],
            ["ECD, Vol 2 (v14)", "The same, plus the mechanics front end", "Algorithms, certificates, design complexity", "Width-based certifying DP; sensor repair (W[2]-hard, ETH-tight); inner/outer sandwich; exact rational influence rows"],
            ["Bounded transduction (v9; 239 pp, 207 results)", "Memory quotient: histories to Nerode classes", "Quantitative core: the frontier", "Hankel rank criteria; AAK/Nehari-type converses; determination-index calculus; multiletter AAK (conditional)"],
            ["Quantum combs (submission 2)", "The process interface", "Quantum face of the constraint", "Intercept principle; normalization-defect calculus; no right or left adjoint; affine non-representability"],
            ["Environmental currying", "Environment tensoring", "Categorical bridge", "No right adjoint except the trivial environment; recovers the no-programming theorem"],
            ["No universal process currying", "Process currying", "Obstruction bridge", "The intercept principle as a universal obstruction"],
            ["Quantum channels (v15; 46 pp)", "Query access to channels", "Quantum price face", "Exact diamond balls; antipodal widths (Borsuk–Ulam); query-uniform compression bounds"],
            ["Quantum instruments (v18; 53 pp)", "The instrument affine hull", "Quantum exact geometry", "Affine dimension d<sub>A</sub><super>2</super>(nd<sub>B</sub><super>2</super>−1); in-radius; complete flat-width classification; qutrit 4/3"],
            ["Monitored circuits (v22 + supplement v5)", "The measurement record", "Statistical estimation of the frontier", "Exact replica mechanics; Born-record large deviations; Z3 closure; PostBQP result"],
            ["Metabolic curvature (v22)", "The FBA constraint switch", "Empirical landing", "κ<sub>μ</sub> measure; 93.4–100% second-order response; r = +0.395 against a −0.083 null"],
            ["Viability companion (v15)", "The viability sheaf", "Compositional home; empirical", "SAVGS; StCon(B) gluing; small-loop viability-holonomy; seven-optic contraction 0.697; terminal-coalgebra maxRAF; HoTT extension"],
            ["General sustainability (Round 32)", "Assessment, sampling, aggregation", "Governance scale", "Obstruction calculus; material ledgers; sampled governance; forecast ladders; ECOMOD identifiability"],
            ["Chess-LLM society", "The next-token interface", "AI application", "Six-role society; CBS-DL; CSR theorem; amplification bound"],
        ],
    },
}

CHAPTERS_A = [
{
"title": "The One-Sentence Picture",
"blocks": [
("p", "Read from above, the corpus is one mathematics. Every line of work — the causal-descent monographs, the rate–distortion theory of bounded sequential transduction, the quantum-comb and instrument papers, the monitored-circuit manuscript, the metabolic-curvature pair, the nine governance papers of the sustainability arena, the chess paper — studies the same object: a system whose behaviour must factor through less information than the world contains. Before asking which behaviour is optimal, the corpus asks which behaviour can be realized at all by an agent with specified observations, causal access, memory, computational resources, and standards of evidence. And when the answer is no, it asks precisely how far short any permitted implementation must fall, and what independently checkable artifact witnesses that answer."),
("p", "Three questions therefore recur in every work, each more refined than the last. Existence: when do locally acceptable behaviours assemble into a global one that survives the bottleneck? Price: what does it cost, in sensors, memory, width, or bits, to widen the bottleneck — and if you cannot, how much error is unavoidable? Proof: when a request fails, what finite, independently checkable object shows it, and where does the failure live? The corpus answers all three, at scales from a two-intersection driving puzzle to a monitored quantum circuit, from a single ribosome-scale metabolic network to planetary governance."),
("p", "The master file “top-down of my work.txt” records four independent syntheses of this corpus, produced by four different models, each given full descriptions of only two works: (a) effective causal descent and (b) the rate–distortion transduction manuscript. All four converged, without coordination, on the same reading of those two pillars — a theory of constrained realizability (astra); existence, proof, and price under observational uniformity (opus 5.5); a rate–distortion theory of bounded observers, with certificates (fable); the Resolution Programme (opus 5). All four also flagged the same limitation: the remaining works arrived as bare identifiers and DOIs, unresolvable from the descriptions supplied. This document closes that loop. Every work in the corpus has now been read at line level; the slot-grids the four syntheses left open can be filled; the picture can finally be stated over the whole of it."),
("quote", "One primitive — behaviour factors through what the agent can distinguish. Two currencies — width and distortion. Three faces — existence and obstruction, price and frontier, proof and certified synthesis. Two walls — combinatorial and analytic. One compositional home, and one epistemology: charts carry certificates, ladders carry monotonicity, limits carry invariants."),
("p", "A serviceable name for the whole remains the one opus 5 gave it: the Resolution Programme — obstruction, price, and proof for systems that must act on less than what is there. The chapters that follow unfold that sentence: the primitive (Chapter 2), its disguises (Chapter 3), the ladder of assembly (Chapter 4), the three faces (Chapter 5), the two walls and the price schedule (Chapter 6), the corpus map with every work docked (Chapter 7), and then the wings — quantum (Chapter 8), biological (Chapter 9), governance (Chapter 10), linguistic (Chapter 11) — before the compositional home (Chapter 12), the epistemology (Chapter 13), and the open frontier (Chapter 14)."),
]},
{
"title": "The Primitive: Factoring Through a Bottleneck",
"blocks": [
("p", "The formal situation is invariant across the corpus. There is a hidden world or history h, and an observational record O(h) — what the sensors return, what the prefix of the past permits, what the finite state can retain, what the interface transmits. A deterministic implementable policy must factor through that record: π = π′ ∘ O. If two histories produce the same available information, no policy can respond differently to them. In the sequential setting, “available information” means the relevant observational history, not merely the current sensor reading; memory can preserve an earlier distinction, but it cannot manufacture a distinction that was never sensed."),
("p", "Impose a finite-state implementation and a second loss of distinctions appears. The controller no longer retains the entire observational history; it maintains a recursively updateable summary, q<sub>t+1</sub> = δ(q<sub>t</sub>, o<sub>t</sub>). Observation identifies hidden histories that the sensors cannot distinguish, and finite memory identifies observed histories that the implementation cannot retain separately. These are related but different limitations, and they have different repairs: more memory can repair forgetting, never blindness. Moreover, not every compression of histories is implementable sequentially — the summary must be updateable from its current state and the next input alone. Causality constrains the representation itself, not only the behaviour. This is the deepest bridge between the two pillars: both ask whether behaviour remains realizable after distinctions have been identified, but they constrain different stages of the identification."),
("p", "Two currencies govern everything in the corpus. Width, or rate, is the capacity of the interface: log|O|, treewidth, state count, Hankel rank, determination index, Weihrauch degree — each domain names the same quantity in its own units. Distortion, or obstruction, is the deficiency of the lift: a fibre conflict, an obstruction datum, a singular value σ<sub>k</sub>, an inner/outer gap. Every theorem in the corpus is a statement about one currency conditional on the other: either a width that suffices for a given distortion, or a distortion floor that no given width can beat. Figure 1 shows the architecture these two currencies organize."),
("figure", None),
("p", "The interface is the unit of cost, and the corpus measures it on two shapes. A tree-decomposition dynamic program must carry across each separator exactly enough information to glue the two sides; the minimum is governed by a gluing matrix whose rows are partial configurations on one side, columns on the other, and entries record compatibility or value. The Hankel matrix H(u, v) = f(uv) is the same object on a path: the past sits on one side, the future on the other, and the present is the separator. Distinct rows give the minimal deterministic interface; the rank gives the minimal linear interface, by Fliess and Carlyle–Paz; the singular values measure what must be lost by forcing a smaller interface. Width, states, and rate are one currency — a width counted in bits of interface state is literally a rate."),
]},
{
"title": "One Constraint, Many Disguises",
"blocks": [
("p", "Observational uniformity says that π(w) = π(w′) whenever the relevant sensor cannot tell w from w′; equivalently, the policy factors through the sensor. The corpus reaches so many literatures because the same constraint recurs under different names, depending on what plays the role of the sensor. Table 1 lists the dialects now confirmed across the whole corpus, from the two described pillars to the quantum, biological, governance, and language-agent works the earlier syntheses could not resolve."),
("table", "disguises"),
("p", "Two rows are the non-obvious ones, and they carry the most weight. Bell locality: a local hidden-variable model is exactly a global policy in which each party’s output, given the hidden variable, is uniform across the other party’s setting — nonlocality is a factorization failure, which is why the CHSH inequality functions as a certificate in the same slot a Farkas vector occupies elsewhere. Computability: computable maps on infinite data are continuous — each finite piece of output is uniform across inputs that agree to some finite precision — so the “uniform” of observational uniformity and the “uniform” of Weihrauch’s uniform reducibility are the same word for the same reason. The title of the first pillar does double duty in the same way: “effective” names both effective descent in the categorical sense and effectivity in the computable sense."),
("p", "The bottom rows generalize the notion of a sensor beyond hardware. An aggregation grid, a reporting convention, a next-token vocabulary, and a sampling regime are as much quotients as a photodetector: each merges worlds that a policy or an institution must then treat identically. This is why the governance corpus and the chess paper belong to the same mathematics as the control and automata works — not by analogy, but because the same factorization constraint, run through the same three questions of existence, price, and proof, produces their results."),
]},
{
"title": "The Ladder of Assembly and the Hankel Bridge",
"blocks": [
("p", "The first pillar organizes failure as a tower of diagnostics. The obstruction datum reports the lowest failing rung and its location; each rung has its own finite witness and its own classical tool, and the classical tools — compactness, Helly, join-trees — each turn a global or infinite check into a finite local one, along three different axes: compactness along the number of worlds, Helly along the dimension of the action space, join-trees along the topology of the contexts. The second pillar adds a quantitative rung on top, and the two together form the ladder every domain in the corpus climbs:"),
("ol", [
 "Local validity — does each fibre admit one uniform admissible action? Failure witness: a fibre conflict, merged worlds with no common action; at most d+1 of them suffice for compact convex actions in ℝ<super>d</super> (Helly), finitely many for compact ones.",
 "Compatibility — do local choices agree on overlaps? Failure witness: a gluing obstruction, necessarily supported on cyclic context structure; probabilistically a Farkas vector, that is, a Bell inequality. Acyclic context structure makes local consistency sufficient — the join-tree theorem, in the tradition of Vorob’ev.",
 "Effective realizability — is there a computable global policy? Failure witness: a reduction showing every global policy computes, for example, a DNR function; the Weihrauch degree measures the gap. Compactness gives existence, not computability — computable trees can lack computable paths.",
 "Bounded realizability — is there one within the resource bound? Failure witness for memory: k+1 pairwise distinguishable histories, or a Hankel block of rank k+1, certifying that no k-state realization exists.",
 "Rate–distortion — with k states, how close can any implementation get? The floor: the (k+1)-st Hankel singular value, by AAK/Nehari-type inequalities.",
]),
("p", "The top rung is why the transduction corpus is a family member rather than a neighbour. The certificates of the first pillar are the distortion-zero slice of the second pillar’s curves: “no k-state machine does this exactly” is a rank statement, and “none gets within ε” is a singular-value statement. The bridge object is the Hankel matrix. Two histories with different rows cannot share a state — a fibre conflict, in the first pillar’s vocabulary; its rank is the minimal fibre count for exact realizability; and where exact realizability fails, AAK and Nehari turn the boolean obstruction (“it fails here”) into a metric one (“it fails by at least σ<sub>k+1</sub>”)."),
("p", "This yields the headline identification of the unified reading, due to opus 5 and confirmed by the corpus at large: the obstruction datum of effective causal descent is the qualitative Hankel spectrum of a sensor bottleneck, and the AAK singular values are the quantitative Čech theory of a memory bottleneck. Nehari’s theorem is a descent theorem — distance-to-extension equals norm-of-obstruction — and AAK is graded obstruction theory. Once this is seen, the four presentation-relative diagnostics of the first pillar read as a degenerate, zero-or-infinity rate–distortion curve, and the multiletter AAK bounds read as the continuous completion of the same ladder. The four external syntheses reached this identification from two works alone; the quantum, channel, and instrument results surveyed in Chapter 8 supply its hardest instances."),
]},
{
"title": "The Three Faces of Every Result",
"blocks": [
("p", "Each work in the corpus proves, for its domain, three theorems of a fixed type. First, an exact criterion with obstruction: the lift exists if and only if the obstruction vanishes, and otherwise a canonical datum locates the first failure. Second, a frontier with a dual lower bound: a Pareto curve of rate against distortion, with the lower bound supplied by duality — never by construction. Third, constructive synthesis with a hardness wall: a width-parameterized algorithm attaining the frontier, plus a proof that the parameterization is optimal, so that no cheaper route exists."),
("p", "The instances cover every domain. The causal-descent pair contributes the diagnostics and obstruction datum, the Bell repair profiles, and the certifying dynamic program over tree decompositions, with NP-completeness, W[2]-hardness, and ETH-tightness as its wall. The transduction manuscript contributes the Myhill–Nerode and Hankel-rank criteria, the AAK/Nehari-type converses, and the Schmidt-pair truncation ladders — each step certified by the next singular value. The combs paper contributes the intercept principle as its exact criterion and affine non-representability as its obstruction; the channels paper contributes exact diamond-ball geometry, antipodal widths as dual lower bounds in the tradition of Borsuk–Ulam, and query-uniform compression bounds as its frontier; the instruments paper completes the flat-width classification — the exact criterion for the whole affine interface. The circuits manuscript contributes the statistical face — Born-record large deviations — with Z3 exact closure as its certified computation and a PostBQP result as its wall. The metabolic pair contributes an empirical frontier, and the governance corpus its minimax dual certificates and forecast ladders."),
("p", "The trichotomy is why the corpus never confuses three different refusals: “no exact lift” (an obstruction), “no cheaper lift” (a frontier), and “no cheaper search for the lift” (a hardness wall). The five-way obstruction taxonomy of the astra synthesis — insufficient information, incompatible local obligations, ineffectivity, insufficient implementation resources, irreducible approximation error — is the diagnostic version of the same discipline, and it is actionable: a failure caused by missing information will not disappear through better optimization, a failure caused by insufficient memory does not require new sensors, and an inconclusive numerical abstraction is not a proof that the underlying mechanical specification is impossible. The governing principle is uniform across the corpus: diagnose the obstruction before choosing the repair."),
]},
{
"title": "The Two Walls and the Price Schedule",
"blocks": [
("p", "Reading the corpora together exposes a structural fact invisible from inside any one of them: the feasible use of a bottleneck is cheap; choosing the bottleneck is hard; and even the best choice has an analytic floor. Hence two independent lower-bound technologies, which the programme shows to be the two walls of the same room. The combinatorial wall: sensor design and sensor repair are W[2]-hard, admit no better than logarithmic approximation unless P = NP, and are ETH-tight — the signature of hitting set. The analytic wall: AAK/Hankel floors — even the right quotient of a given width cannot beat σ<sub>k</sub>. Neither wall is visible from inside a single work; together they say that partial observability is not a nuisance to be engineered away but a conserved quantity with a price schedule."),
("p", "The reason for the division of labour is precise, and it belongs to fable’s synthesis: a partition quotient is a 0/1 projection, and a subspace quotient is an orthogonal projection; relaxing the former to the latter converts hitting-set into an eigenvalue problem. The integrality gap between partition and subspace quotients is therefore the price of physical realizability. The practical consequence is a division of labour that runs through the whole corpus: choosing the sensor is provably hard even to approximate, while pricing it is spectral and computable in time polynomial in the size of a finite section — the converses do not solve design, but they bound it from below cheaply."),
("table", "prices"),
("p", "The schedule deserves a reading, because it is the corpus’s empirical identity card. The absent-minded driver and CHSH are the same table in two dialects — zero bits against one bit, 4/3 against 4, 3/4 against 1 — and each entry carries its certificate, which is what makes the price a theorem rather than an observation. The physics entries measure the same currency in continuum mechanics: the uniform chain’s inverse (K<super>−1</super>)<sub>ij</sub> = min(i,j)/k decays not at all, so thresholding fails and combinatorial width is maximal, yet every past–future block has rank 1 and each cut needs only two scalars — total load and first moment — which is why rank-aware methods stay polynomial where width explodes. The quantum entries are exact rather than asymptotic: the instruments geometry closes the integrality gap by hand, and the monitored-circuit entries close it by machine, with Z3 two-sided certificates. Glover’s Hankel-norm model reduction is the analytic shadow of sensor repair, and balanced truncation the analytic shadow of choosing which states to observe."),
]},
{
"title": "The Corpus Map: All Works on One Grid",
"blocks": [
("p", "The four external syntheses each ended with a slot-grid: a matrix of domain against face, the two described works placed, and empty cells marked with the notation of an unfinished proof. Because the remaining works have now been read in full, the grid can be closed. Table 3 docks every corpus line — the two pillars, the quantum trio, the channel and instrument papers, the monitored-circuit manuscript, the metabolic pair, the sustainability arena, and the chess paper — onto the bottleneck it studies, the slot it fills, and the signature results it contributes."),
("table", "map"),
("p", "Four patterns emerge from the filled grid, and they are the substance of the unification. First, the quantitative face of contextuality — the cell opus 5 guessed would be filled by “rate–distortion of nonlocality” — is filled twice over: by query-uniform compression bounds for channels and by the exact affine geometry of instruments, so the quantum interfaces carry their own price lists, in closed form. Second, certified synthesis on the sequential side — the algorithmic companion the automata line lacks — remains the genuinely open cell: the spectral converses bound it, but nothing yet constructs it. Third, the statistical estimation of the frontier, guessed empty, is filled by Born-record large deviations and by the finite-sample Bell tests of the first pillar — the record of a monitored circuit is itself a bounded observer, and its large-deviation rate function estimates the frontier from data. Fourth, the trust layer is filled with named artifacts: Lean’s InterceptCert, the Z3 closure suites, the pinned reproducible computational studies."),
("p", "The map also settles a doubt the four syntheses could not: the trailing DOIs and identifiers that arrived unread are companion deposits of this same programme — texts, artifacts, and datasets behind the pillars — not foreign works requiring the picture to be revised. Nothing in the corpus adds a rung or contradicts the architecture; everything fills a slot the architecture predicted. That is the strongest evidence the unification is real rather than projective: the grid was drawn from two works, and the other eleven docked without forcing."),
]},
]
