# -*- coding: utf-8 -*-
"""rp_content_b.py — The Resolution Programme: chapters 8-14 (content module)."""

CHAPTERS_B = [
{
"title": "The Quantum Wing",
"blocks": [
("p", "In the quantum works the quotient is a process interface — a comb, an environment tensoring, a query, an instrument — and the constraint acquires its sharpest statements. The combs manuscript states it as a normalization defect and an intercept principle: what a comb can realize is bounded by what its interface intercepts, and the affine non-representability formula d<sub>C</sub><super>2</super>(d<sub>A</sub><super>2</super>−1) + d<sub>C</sub><super>2</super>d<sub>A</sub><super>2</super>d<sub>B</sub><super>2</super>(d<sub>D</sub><super>2</super>−1) counts exactly which points of the ambient affine space no physically realizable comb reaches. The adjoint results are the categorical form of the same verdict: no right adjoint and no left adjoint — the interface cannot be transcended by pure algebra. Environmental currying sharpens this further: tensoring by the environment admits a right adjoint only for the trivial environment, and the failure recovers the no-programming theorem. No universal process currying then isolates the intercept principle itself as the universal obstruction — the quantum statement that not every global behaviour factors through a chosen process interface."),
("p", "The channel and instrument papers are the quantum price face, and they give the frontier its exact geometry. Query-uniform compression bounds are the quantum rate–distortion statement: how much any uniform query protocol must lose when it compresses channel discrimination to a bounded query budget. The exact diamond balls and antipodal widths of the channel paper make the dual lower bound geometric — the Borsuk–Ulam theorem supplies the antipodal bound, a topological Farkas certificate in the same slot the CHSH inequality occupies classically. The instruments paper then completes the affine interface’s classification: affine dimension d<sub>A</sub><super>2</super>(nd<sub>B</sub><super>2</super>−1), in-radius 2/(nd<sub>B</sub> min{d<sub>A</sub>, d<sub>B</sub>}), a complete flat-width classification, and the qutrit value exactly 4/3. These are exact prices rather than asymptotics — the analytic wall with the integrality gap closed by hand, dimension by dimension."),
("p", "The monitored-circuits manuscript is the statistical face of the programme at its current frontier. Exact replica mechanics and Born-record large deviations treat the measurement record of a monitored circuit as itself a bounded observer of the quantum state, and characterize the large-deviation rate function of what that observer can infer — the finite-sample estimation of the frontier, run on the hardest interface the corpus studies. The v22 exact-closure suite shows the certificate discipline operating there in earnest: Z3-verified two-sided certificates, Λ(2) values pinned at −0.1219, −0.1239, and −0.1245 for L = 8, 12, and 16, the ESS exponents corrected to 0.0340, 0.0349, and 0.0353, and the complexity-theoretic wall stated in PostBQP terms. At this writing the v23 computation of the L = 8 rung is still running, at chunk 4161 of 8295 — the programme is not only a description of frontiers; it is, at this moment, computing one."),
]},
{
"title": "The Empirical Landing: Biology as a Working Instance",
"blocks": [
("p", "The metabolic pair is where the programme touches data, and it is the corpus’s only empirical landing. The main manuscript defines a discrete curvature measure κ<sub>μ</sub> for flux-balance analysis and shows that it predicts transcriptional regulation in E. coli: second-order response concentrates at constraint-switch boundaries at rates between 93.4 and 100 percent; the correlation with transcriptional regulation is r = +0.395 across 424 genes, while the protein layer shows a null of r = −0.083; 66 percent of regulatory cycles show non-reversion with slope 1.00; and the cycle-response association is ρ<sub>S</sub> = 0.865. The theorem map — the value–flux coupling identity, the refinement–resolution bridge, Monge–Ampère atoms — is the exact-criterion face of the programme, and the Keio and iJO1366 validation chains apply the certificate discipline to wet-lab data, strain by strain."),
("stats", [("+0.395", "transcription-layer correlation, 424 genes"), ("−0.083", "protein-layer null — the differential test"), ("0.865", "cycle-response association ρ<sub>S</sub>")]),
("p", "The differential pattern is the point, and it is characteristic of the whole programme: curvature predicts the transcription layer and not the protein layer, so the signal concentrates exactly where the resolution quotient bites. Biology reads as a working instance of the theory — the cell is a bounded observer whose regulatory policy factors through metabolic viability, and regulation concentrates at constraint-switch boundaries, where the quotient’s curvature is high. The empirical claim, made quietly, is large: this is not only normative mathematics; a four-billion-year-old optimizer implements its predictions, and implements them in the layer where the theory says the obstruction lives."),
("p", "The viability companion gives the same landing its compositional home. SAVGS organizes the viability geometry; StCon(B) makes the compatibility rung functorial as a sheaf of constrained behaviours; the small-loop viability-holonomy theorem prices regulation around metabolic cycles; and the seven-optic composition carries a Banach contraction with constant 0.697 — below 1, hence a constructive fixed point — with a fatigue exponent of 3/2. The terminal-coalgebra characterization of maxRAF places autocatalytic closure at a universal fixed point of the viability interface, and the stratified homotopy-type-theoretic extension (proof-sketch status, honestly flagged as such in the manuscript itself) is the programme’s own discipline applied to its own frontier. The Keio E12–E26 verdict chain closes the loop from sheaf to strain."),
]},
{
"title": "The Governance Scale",
"blocks": [
("p", "The general-sustainability corpus — Round 32 of the arena: five core papers, the four-paper wave E, a five-layer successor manuscript, six computational notes, and the ECOMOD study from the second agent — is the programme at planetary scale, and it names itself accordingly: its second paper is an obstruction calculus. The objects are assessment systems, material ledgers, delay dynamics, sampled governance, and forecast ladders with interventions; the notes supply computational certification, worked systems, exact belief computation, and probabilistic sufficiency — the certificate discipline transposed from solvers to institutions. What the governance corpus adds that the mathematics cannot is stakes and asymmetry: a mis-sampled governance grid is not a theorem failing, it is a policy succeeding on the wrong quotient, with the error surfacing a decade later in the ledger."),
("p", "Each paper runs the trichotomy at institutional scale. Assessment separation (v62) separates prediction from prescription — the realizability of policy under assessment resolution, with the two failure modes priced separately. The obstruction calculus (v55) and its notes certify when institutional constraints cannot be jointly satisfied and what relaxation would cost. Material ledgers (v32) treat accounting as a quotient on physical flows, with identifiability conditions for what the books can and cannot see. Delay dynamics (v41) is guarded feedback in institutional time. Sampled governance (v47) is literally sensor design for institutions — what must be monitored, how often, at what resolution, for a target to remain attainable. Wave E’s cod and Edwards forecast ladders (v59, v16) and their interventions (v23, v15) are refinement ladders carrying monotone certified forecasts — the inner/outer sandwich at the scale of fisheries and planetary boundaries — while the minimax dual-certificates note supplies the duality face, and ECOMOD (v37) shows how aggregation conceals composition: biocapacity drawdown is unidentifiable from aggregated accounts, the resolution-limited quotient made fiscal."),
("p", "Read together with the rest of the corpus, the governance works are the programme’s demonstration that its refusals scale. The same three questions — can this institution’s policy factor through what it monitors; what does finer monitoring cost; what certificate witnesses the answer — that organize a two-node driving puzzle organize a planetary accounting system, and the answer the corpus gives at both scales is the same: certify the obstruction, price the repair, and refuse unwitnessed optimism."),
]},
{
"title": "The AI Wing: Bounded Observers Made of Language",
"blocks": [
("p", "The chess paper — a society of specialised LLMs overcoming autoregressive myopia — is the programme instantiated on language agents, and its diagnosis is pure corpus: the next-token interface is a quotient. A model conditioned on its own output stream cannot distinguish futures that its vocabulary merges; myopia is therefore not a bug of training but a resolution constraint of the interface, exactly as a sensor suite merges worlds and a finite state set merges histories. The repair the paper builds is the repair menu of the corpus in full: the six-role society (CBS-DL) specializes sensors, since roles attend to different features of the position; it allocates memory, since roles maintain distinct state; it re-architects computation, since roles compose; and it refines the certified model through deep lookahead, accepting bounded amplification rather than unbounded promise."),
("p", "The theorems sit in the canonical slots. The CSR theorem and the amplification bound of Theorem 2* are the frontier and the wall: what amplification a society of bounded observers can buy, and the bound no such society can beat — the duality face for language agents. Deep-lookout planning is the width-parameterized synthesis. The correspondence is exact enough that the paper can be read as the programme’s existence proof in silicon: bounded observers, composed under a graded interface, attaining a certified frontier that no single bounded observer reaches — which is, not coincidentally, the chess society’s empirical result against monolithic baselines."),
]},
{
"title": "The Compositional Home",
"blocks": [
("p", "The categorical works are not decoration on the corpus; they are its wiring diagram. The morphism theory of the first pillar — functoriality, sequential and parallel composition, guarded feedback — and the transducer calculus of the second — cascade, product, feedback — are the same object seen from two directions: a monoidal category with trace, doubly graded by rate and distortion. Objects are interfaces; morphisms are policies and transducers; composition adds rates and accumulates distortion subadditively; guarded feedback is the trace, guarded precisely so that the accumulation stays well-founded. This is the level at which the mechanics front end, the CSP encodings, the Bell scenarios, the automata, the optics, and the combs become the same kind of thing and can be wired together, with certificates composing alongside the behaviours they certify."),
("p", "Each categorical construction in the corpus fills a slot in that home. Environmental currying is the interface algebra: the intercept principle is what remains of currying when the environment is physical, and the no-programming theorem is its obstruction wall. Sheaf gluing StCon(B) is the compatibility rung made functorial. The seven-optic composition of the viability companion is the graded wiring of constrained behaviours, and its Banach constant (0.697) is the distortion accounting of that wiring made constructive. The terminal-coalgebra maxRAF makes autocatalytic closure a fixed point of the viability interface — the empirical landing expressed in the compositional home — and the homotopy-type-theoretic stratification extends the home upward, at proof-sketch status, in the direction where guarded fixed points become homotopy fixed points."),
("p", "One quantitative law remains genuinely open in the home, and the two pillars pose it jointly: feedback. Guarded feedback is the combinatorial twin of feedback interconnection of transducers, and the quantitative law for how obstructions compose under feedback should be small-gain-shaped in Hankel norm — distortion accumulating around a loop should be governed by the product of the loop’s interface norms. No work in the corpus yet proves it; every work in the corpus is arranged as if awaiting it."),
]},
{
"title": "The Methodological Spine",
"blocks": [
("p", "The programme’s epistemology is unusual, and it is stated as a feature rather than apologised for: diagnostics, widths, and certificates are presentation-relative — properties of a chart, not of the abstract problem. Complexity belongs to a problem-presentation pair, morphisms transport it, and the curves of the second pillar are the exchange rates between presentations. The frontier is the chart-invariant content. Refinement ladders — width-adaptive sparsification, multiletter blocking, mesh refinement, tree-decomposition improvement, forecast ladders — are the mechanism by which chart-relative certificates converge monotonically to invariant truth: an inner/outer sandwich, P<sub>inner</sub> ⊆ P<sub>true</sub> ⊆ P<sub>outer</sub>, closing on the real policy space from both sides. The epigram that closes opus 5’s synthesis is the corpus’s own answer to how proof-producing computation can speak about continua and hidden states at all: charts carry certificates; ladders carry monotonicity; limits carry invariants."),
("p", "The second commitment is proof-relevant negatives: every “no” in the corpus is witnessed, and there are no unwitnessed negatives anywhere in it. Fibre conflicts witness local failure; Farkas vectors and Bell inequalities witness contextuality; DNR reductions witness ineffectivity; rank k+1 blocks and Hankel singular values witness memory floors; antipodal widths witness channel floors; Z3 two-sided certificates witness exact closure in monitored circuits; Lean’s InterceptCert witnesses the intercept principle by proof assistant. Trust accordingly moves from solvers to small checkers, and the SAT/CP-SAT/MILP studies of the second pillar are simultaneously performance comparisons and N-version differential testing, pinned by reproducible artifacts. The sandwich separates three outcomes and refuses to collapse them: a policy in the inner set certifies feasibility; an empty outer set certifies infeasibility; and an empty inner set with a nonempty outer set marks unresolved uncertainty — never silently resolved."),
("p", "Two kinds of approximation are kept rigorously distinct, and confusing them is the corpus’s definition of error. Behavioural approximation deliberately tolerates distortion in the implemented behaviour; certified abstraction approximates the analysis while preserving sound conclusions about a hard specification. A small average distortion is not a worst-case safety guarantee. And when the input is a frequency table rather than an exact model, a certificate becomes a test with a controlled error rate — the finite-sample Bell tests of the first pillar and the Born-record large deviations of the circuits manuscript are the same move, executed on classical count data and on quantum measurement records respectively."),
]},
{
"title": "The Open Frontier",
"blocks": [
("p", "A unified picture earns its keep by making the open problems legible as cells of the same grid. The frontier of the programme, as it stands at this writing, is the following:"),
("ol", [
 "The multiletter AAK theorem — explicitly conditional in the transduction manuscript, and the deepest single open problem in the quantitative core. The block-length ladder is the continuous completion of the assembly ladder; its missing rung is the analytic wall’s top course.",
 "Certified synthesis on the sequential side — the one slot the filled grid still leaves empty: the algorithmic companion for automata and transducers that the certifying dynamic program is for contexts. The spectral converses bound it; nothing yet constructs it.",
 "The partition–subspace bridge — a theorem, not a vocabulary, equating the integrality gap between 0/1 and orthogonal projections with the price of physical realizability, with spectral certificates (Courant–Fischer witnesses, checkable by exact semidefinite tests) joining the typed certificate family.",
 "The graded category with trace, and the small-gain law in Hankel norm for how distortion composes around guarded feedback — the compositional home’s missing quantitative law.",
 "Rank-aware width for physics — dynamic programs carrying sufficient statistics (total load and first moment per cut) that stay polynomial where combinatorial width explodes, with Hankel spectra as their natural converse; the rank-1 blocks of the chain inverse are the paradigm.",
 "Statistical estimation of obstruction data — Born-record large deviations as the beginning of a quantitative obstruction profile: a distortion floor for each rung of the ladder, estimated from records rather than computed from models.",
 "The three named open problems of the transduction line — intrinsic multi-alphabet Hankel equality, the exact symbolic grounding gap, and the non-degenerate two-term active decomposition.",
 "Live computations — the v23 L = 8 rung (at chunk 4161 of 8295 at this writing), the figshare DOI, and the union citation list: the corpus’s own pre-submission blockers, tracked with the same status discipline as its theorems.",
]),
("p", "For a reader entering the corpus with this picture in hand, the reading order that follows the architecture rather than the chronology is: Effective Causal Descent, Volume 1, then Volume 2; the unified transduction manuscript (v9); the combs submission with the two currying papers; the channel and instrument papers; the monitored-circuits manuscript with its supplement; the metabolic pair; the sustainability compendium of Round 32; and the chess paper — with the master file, “top-down of my work.txt”, as the prism through which the whole is meant to refract."),
("p", "Read whole, the corpus is a single instrument played across eight registers, and its coherence is architectural rather than thematic: one primitive, two currencies, three faces, two walls, one compositional home, one epistemology. What the union asserts that no single volume does is exactly what opus 5 said, now confirmed across every line of the corpus: contextuality, finite-state approximation, and treewidth-bounded synthesis are one subject — bounded-interface factorization; Farkas, Nehari, Čech, and dynamic-programming refutation certificates are one duality, instantiated four ways; every “no” is proof-relevant; hardness comes in exactly two flavours, complementary rather than competing; and presentation-relativity plus monotone refinement is a sufficient epistemology for certified reasoning about partially observed physical systems. That is the grand picture. The works are its witnesses."),
]},
]
