# -*- coding: utf-8 -*-
"""tv_content_b.py — A Theory of Bounded Observation (Vol IV): chapters 7-12."""

CHAPTERS_B = [
    {"title": "The Laws the Theory Generates",
     "blocks": [
        ("p", "A theory earns the word by generating its laws as equations of state — "
              "relations among state variables and controls that hold across the domain, "
              "with named refuters. Volume III legislated four; the confrontations have "
              "now added four more, each carried by numbers that did not exist when "
              "Volume III closed. They are stated here together for the first time, and "
              "the register is deliberate: every law below is either proved in a "
              "fragment, measured at a boundary, or certified as an envelope, and each "
              "says which."),
        ("p", "<b>Law 4 — the phase-boundary chain.</b> The record free energies of the "
              "monitored circuit break analyticity at the annealed replica points, which "
              "form a receding chain: 0.233810 exactly, 0.305(3), 0.382(1) — all three now "
              "measured — and 0.47 to 0.48, "
              "0.47 to 0.48, with the boundary class running along the q = n Potts "
              "line and the transition turning first order at n = 5. The first three "
              "rungs are now measured objects — the first to five decimals by exact "
              "arithmetic, the second by a rebuilt chain whose every anchor "
              "reproduced — and the chain's receding direction (away from the quenched "
              "0.1597(8)) is itself a law-like fact: no sequence of annealed points "
              "converges to the Born-weighted transition from above. Refuter: a kink "
              "that fails to localize inside its certified window at any rung, or a "
              "chain that turns non-monotone in n. <b>Law 5 — the Onsager law of record "
              "phases.</b> At each boundary the record susceptibility diverges "
              "logarithmically, chi = c x (-ln|p - p_c|) + O(1), with the finite-L peak "
              "growing as the log of the system size and the response concentrating "
              "onto the closing relative gap at rate c/L. Measured: coefficient 0.32, "
              "R-squared 0.9902, peak growth 0.641 ln L, gap closure X_sigma/L. This is "
              "Onsager's specific heat transplanted whole into the statistics of a "
              "measurement record — a sentence that could not even be typed before the "
              "scan ran."),
        ("p", "<b>Law 6 — the layer-separation law</b> (cellular sector): epsilon-laws "
              "at the LP flux layer, set by constraint geometry; k-laws above it, set "
              "by Lipschitz products; the LP layer saturates in one traversal wherever "
              "constraint sets nest. Measured on both sides — the LP rate 0.249 with "
              "R-squared 1.000 and the linear drift law at slope 1.001 below, the "
              "cascade envelope 0.361 above — and proved in the nesting case. Refuter: "
              "a per-cycle geometric relaxation at any LP flux layer. <b>Law 7 — the "
              "defect-pricing law</b> (compositional sector): in-span correlation "
              "defects price factorization quadratically and are absorbed to first "
              "order by the optimum; transverse defects price the value linearly and "
              "evenly; the composite-of-optima never pays more than twice the defect "
              "norm; and chained defects accumulate under the small-gain inequality. "
              "Proved as Theorem VIII and witnessed in exact arithmetic. Refuter: an "
              "instance where the in-span excess is linear or the transverse excess "
              "nonzero. Together with Laws 0 through 3 these are the theory's seven "
              "equations of state — the number is not the point; the grammar is: each "
              "law binds named observables, holds across a named sector, and dies by a "
              "named experiment."),
     ]},
    {"title": "New Physics After the Confrontations",
     "blocks": [
        ("p", "The physics dossier of Volume III had four entries: record phase "
              "transitions, obstruction as observable, the one-wall hypothesis, and the "
              "curvature-regulation correspondence. The confrontations have upgraded the "
              "first, installed the second concretely, and added one entry that did not "
              "exist. The record phases are no longer a prediction awaiting a scan: "
              "they are a measured object with a phase diagram, an Onsager law, and a "
              "response mechanics. What is physically new is not merely that a "
              "measurement process has phases — it is <i>which</i> observable carries "
              "them: not the entanglement, not the purity, but the Born record's "
              "large-deviation family, with the ESS budget — an operational, "
              "sample-counting quantity — inheriting the boundaries. A quantity that "
              "an experimentalist computes to decide whether a Monte Carlo run can be "
              "trusted turns out to be the order parameter carrier of a phase diagram. "
              "That is the kind of statement the mandate was asking for, and it is now "
              "load-bearing rather than decorative."),
        ("p", "The new dossier entry is the layer separation, and its physical content "
              "is a statement about where laws can live in a cell. The LP flux layer — "
              "the layer that every constraint-based model of metabolism actually "
              "computes — provably cannot carry memory through closed cycles, because "
              "its geometry is nested and its projections are lazy: it settles in one "
              "traversal. The epsilon-laws it does carry (the linear drift, the "
              "curvature concentration, the 93.4 to 100 percent second-order response "
              "at active-set boundaries) are geometry laws — Friedrichs angles and "
              "active-set walls, not dynamical systems. Everything that unfolds over "
              "repeated cycles — adaptation, fatigue, the 3/2 exponent, the 0.361 "
              "envelope — must live in the post-translational layer that the LP model "
              "does not even represent. The theory thus sharpens the corpus's own "
              "where-does-memory-live deduction from an inference into a geometric "
              "exclusion, and the two routes to the conclusion — transcriptional "
              "correlation on one side, projection nesting on the other — are "
              "independent, which is what makes the conclusion hard."),
        ("p", "The third physics upgrade is quieter but structural: the convergence of "
              "the two continuations on one inequality. When the repaired "
              "approximation-theoretic lemma and the thermodynamic cascade law turn "
              "out to be the same inequality — defects attenuated by products of "
              "Lipschitz constants, summed geometrically, bounded by the small-gain "
              "denominator — the programme acquires its first genuine unification "
              "below the level of vocabulary. The AAK floor on one side and the ESS "
              "budget on the other were both, all along, instances of one bookkeeping "
              "rule for bounded observers: what you cannot absorb, you carry, "
              "discounted by what transmits you. The one-wall hypothesis of Volume III "
              "gains a second face from this: if compactness failures and spectral "
              "tails and thermodynamic budgets are one phenomenon, then the search for "
              "a single modulus behind them is not category error but programme."),
     ]},
    {"title": "New Capabilities: The Instrument Register",
     "blocks": [
        ("p", "Capability one: <b>phase-flagged certified telemetry</b>. The LD "
              "telemetry of Volume III reported record exponents with exact-arithmetic "
              "certificates; the confrontations add the flags. The ESS budget curve now "
              "carries two certified phase boundaries — 0.233810 and 0.305(3) — with "
              "the kink-localization protocol attached: run the crossing ladder, "
              "interpolate the susceptibility peak, check the Onsager form, and flag. "
              "An experimentalist operating the monitor need no theory at all to use "
              "this: the instrument tells them whether their sampling budget is "
              "analytic in the control or sitting on a boundary, and the answer is "
              "certified to the anchors. Capability two: <b>the layer-resolved assay</b> "
              "— a protocol for any constraint-based organism model: run the closed "
              "genotype cycles (expect one-pass saturation, which certifies the LP "
              "layer is clean); run the sized parameter alternations (measure the "
              "substrate's own geometric rate; check the drift law's slope near 1); "
              "run the cascade model's extremal instance (recover 0.361 as the "
              "envelope). The assay separates the layers of any measured relaxation "
              "before any biochemistry is done, and its readout — which layer carries "
              "a k-law — is a design input for where to intervene."),
        ("p", "Capability three: <b>the defect-decomposition diagnostic</b>. Theorem "
              "VIII turns a mathematical dichotomy into an instrument: given an "
              "observed correlation defect in any composite system, project it onto "
              "the structured span of the composite class and price the two parts — "
              "the in-span component is the one that shifts the optimal operating "
              "point (quadratically cheap to ignore, linearly informative to track), "
              "while the transverse component is the one that raises the floor and "
              "must be paid in width. The protocol is three lines of linear algebra "
              "and one bounded check, and it applies wherever the programme's "
              "compositional sector applies — channel compositions, instrument "
              "families, cascade stages. Capability four: <b>the "
              "anchor-reproduction-first experimental method</b> itself. Every "
              "confrontation in this volume began by reproducing the apparatus's own "
              "certified numbers — the benchmark table to six decimals, the spectral "
              "anchors to six decimals, the rank formula, the endpoint eigenvalues — "
              "before taking a single new reading. That discipline is what let a "
              "from-scratch rebuild of a three-replica chain carry conviction at "
              "L = 8, and it is exportable: it is the difference between an experiment "
              "and an assertion, operationalized."),
     ]},
    {"title": "The Falsifiability Ledger",
     "blocks": [
        ("p", "The ledger closes the volume the way it closed the last one, because "
              "the discipline is the theory's spine. Table 3 updates the prediction "
              "register: of the entries carried over from Volume III, the kink "
              "localization is confirmed at the exact level; the Onsager signature is "
              "confirmed with R-squared 0.99; the Lambda(2) boundary is confirmed as a "
              "ladder; Prediction 1 — the 0.361 rate — receives a layer-resolved "
              "verdict, refuted as an LP-layer universal, confirmed as the cascade's "
              "certified slowest case, with the layer separation itself promoted to a "
              "law; and the linear drift law is independently reproduced at slope "
              "1.001. The new entries extend the register in the directions the theory "
              "opened: the n = 4 boundary is now measured — crossings (4,6) 0.3583, (6,8) 0.3791 against the manuscript 0.35820 / 0.37899 / 0.3823, the "
              "R-ladder 0.1314 / 0.1827 / 0.2140 against the manuscript 0.1315 / 0.1829 / 0.2142 / 0.2378 on the marginal target, the multiplet "
              "order exact — and the transfer behaviour of the LP-layer constant (the theory "
              "says 0.249 is a property of the glucose-acetate constraint pair, so "
              "other pairs and other organisms should yield their own constants — "
              "predictable variety, not noise); and the defect-dichotomy's "
              "experimental signature in any composite system whose defects can be "
              "decomposed."),
        ("table", "predictions"),
        ("p", "Table 4 is the provenance ledger — the honesty register made auditable. "
              "Its discipline is unchanged from Volume III: every load-bearing claim "
              "is typed as proved-in-corpus, proved-here, measured-here, "
              "reproduced-here, verified-here, or conjecture, with the witness named. "
              "The session's contribution to the register is unusually clean on the "
              "reproduction side — the confrontations reproduced the corpus's own "
              "numbers before producing any of their own, which is why the new numbers "
              "(a five-decimal kink, a second-boundary ladder, a three-layer verdict) "
              "can be stated without hedging — and deliberately conservative on the "
              "conjecture side: the Resolution Second Law, the equality D* = sigma*, "
              "and the one-wall identification remain exactly where Volume III left "
              "them, open, with their witnesses."),
        ("table", "provenance"),
     ]},
    {"title": "What the Theory Is and Is Not",
     "blocks": [
        ("p", "The theory is a formalism with a domain: the class of systems whose "
              "behaviour factors through a bounded observer — monitored quantum "
              "circuits, constraint-based metabolic models, composite channels and "
              "cascades, and the sequential transductions of the rate-distortion "
              "corpus. Within that domain it fixes state, controls, potentials, "
              "phases, dynamics, and a measurement protocol, and it generates laws "
              "with refuters. It is not a single mechanism: the LP layer's Friedrichs "
              "angle and the cascade's Lipschitz product are different mathematics, "
              "and the theory does not pretend otherwise — what it unifies is the "
              "grammar (state, price, envelope), not the mechanism. It is also not "
              "finished, and the register says where: the second law of the "
              "formalism — obstruction implies entropy production — remains a "
              "conjecture with witnesses; the equality D* = sigma* remains open "
              "beyond the isometry case; the one-wall hypothesis remains the pure "
              "programme physics; and the phase diagram has three measured rungs out "
              "of a predicted four."),
        ("p", "What the theory is <i>not</i> is equally specific. It is not a claim "
              "that everything is thermodynamics — the transplant works because the "
              "record statistics happen to have an exactly solvable Ising sector, "
              "and the exactness is what carried the confrontation; where no exact "
              "sector exists the theory's predictions will have error contracts, not "
              "certificates. It is not a claim that 0.361 is universal — the "
              "confrontation refuted that reading, and the law that survived is the "
              "layer law. And it is not a claim that the corpus's manuscripts "
              "anticipated their own unification: the four external syntheses of the "
              "master file converged on constrained realizability but could not "
              "state any of the seven laws, because the laws needed the bridges of "
              "Volume II and the legislation of Volume III before they existed to be "
              "measured. The theory's refutation condition is correspondingly global: "
              "a fourth substrate, inside the domain, on which the postulates fail — "
              "potentials that do not exist, closure that breaks, self-averaging that "
              "dies, boundaries that do not localize — would not trim the theory but "
              "topple it, and the theory is stated so that such a substrate can be "
              "looked for."),
     ]},
    {"title": "The Programme After Four Volumes",
     "blocks": [
        ("p", "Four volumes, four grammatical stages. Volume I built the dictionary: "
              "every corpus work docked into the slot-grid the external syntheses "
              "left open, one mathematics named. Volume II built the bridges: the "
              "external reviewers' theorems adjudicated, corrected, and restated with "
              "their open links isolated. Volume III legislated: four laws, six "
              "theorems, nine predictions, five capabilities — the pile reorganized "
              "as instances. Volume IV, this one, built the theory and took it to "
              "the numbers: the formalism, the three confrontations, two more laws "
              "and two more theorems, and the first measured rungs of the phase "
              "diagram. The arc is visible in the objects: from a map, to bridges, "
              "to laws, to a system with state variables — which is the arc the "
              "mandate demanded when it insisted on theories rather than theorems."),
        ("p", "The queue that remains is shorter and sharper than the one Volume III "
              "left, and its head is now cleared: the n = 4 boundary was measured "
              "this session — crossings (4,6) 0.3583, (6,8) 0.3791 against the manuscript 0.35820 / 0.37899 / 0.3823, the marginal R-ladder on its "
              "logarithmically slow approach to 1/4, the multiplet order exact, the "
              "endpoints exact — so the receding-ladder law is now measured at "
              "every rung it predicts below the first-order point (the n = 5 "
              "diagnostics remain the manuscript's own computation). Order two: the qutrit obstruction meter on hardware — the flat-width "
              "ladder and the 4/3 index are unchanged from Volume III and remain the "
              "programme's cheapest direct physics test. Order three: the equality "
              "D* = sigma*, now flanked from both sides — the thermodynamic side "
              "(the cascade's fixed point) and the approximation side (the repaired "
              "lemma's optimum) — converging on the same inequality from opposite "
              "directions, which is historically how equalities get proved. Order "
              "four: the one-wall hypothesis, still the programme's one piece of "
              "pure physics, still stated so that exhibiting a compactness modulus "
              "that does not control a spectral tail would kill it. The honest "
              "summary of the session is that the programme has, for the first time, "
              "run its own predictions to ground: two confirmed, one resolved by "
              "layer, one refuted and repaired into a law, and — in the extended "
              "round — the fourth-replica boundary measured and confirmed against "
              "the manuscript's chain at three crossings and a marginal amplitude "
              "ratio on target. A theory that has met "
              "numbers and survived the meeting is no longer a synthesis. It is a "
              "candidate physics."),
        ("quote", "Two independent routes — one from transcriptional correlation, one "
                  "from projection geometry — land on the same layer of the cell. "
                  "That is what makes the conclusion hard."),
     ]},
]
