# -*- coding: utf-8 -*-
"""vol10_content_b.py — The Rank-Defect Theorem (Vol X): chapters 7-12.
All statements anchored to the session's verification batteries."""

CHAPTERS_B = [
    {"title": "The scope theorem — the answer", "blocks": [
        ("p", "The classification assembles into the scope theorem, the "
              "answer to the ordered question. The processes satisfying "
              "arrow iff rank defect are exactly those whose "
              "non-reversibility is spectrally carried inside the "
              "observable's visible spectrum. The circulant (abelian) "
              "families with arrow-carrying observables are the canonical "
              "class: within them the reversible slice coincides with the "
              "spectral-merging locus, so turning the arrow off forces "
              "the degeneracy that collapses the rank, and the "
              "equivalence is a structural identity rather than a "
              "coincidence. Beyond the abelian class both failure "
              "quadrants have positive measure — the real-spectrum "
              "irreversibles of the hidden arrow and the symmetric "
              "mode-splittings and Gaussian complexes of the fake arrow "
              "— and the equivalence becomes the exception that the "
              "ring's structure buys."),
        ("p", "In the corpus's language: the rank defect is the abelian "
              "shadow of the arrow. The arrow itself — the reversal "
              "divergence of the full law — is the record-theoretic "
              "object, monotone under sensors, inherited or destroyed but "
              "never fabricated; the Hankel rank sees only the "
              "second-moment, abelianized projection of that law, and on "
              "the abelian families the projection is faithful. This is "
              "the same abelianization that Volume VIII measured "
              "algebraically (the Parikh reduction, the circulant class "
              "where the transport sandwich closed): the rung was the "
              "place where the free structure collapsed to its commutative "
              "shadow, and it is the same place where the arrow becomes a "
              "rank. The BT2 stratum (the Hankel memory) and the BT3 "
              "stratum (the reversal intercept) meet at the register, and "
              "the meeting is exact only on the abelian slice."),
        ("p", "The chat's final synthesis lands here with its correction "
              "intact: 'it and bit from record' requires the record to "
              "have a history, and the one-way valve says the history's "
              "asymmetry is bounded by the world's. A record that launders "
              "the chirality — the parity sensor, the reflection orbits, "
              "the Gaussian stratum — can carry complete information "
              "about correlation structure while carrying none of the "
              "arrow; a record that keeps the chirality keeps an arrow "
              "it cannot amplify. The three strata of Task 14's "
              "stratification (classical reality, thermodynamic "
              "irreversibility, quantum coherence) now have their "
              "sensor-theoretic boundary: the arrow is a chirality "
              "carried by the circulation, the record's fidelity to it is "
              "measured by the block reversal KL, and the rank defect is "
              "the abelian shadow that fidelity casts on the covariance."),
    ]},
    {"title": "Experiment 1 — the setup and the compression", "blocks": [
        ("p", "The chat's first experiment names WikiText-103 or 'a "
              "synthetic task with known finite-state structure' as its "
              "benchmarks; the second branch is the scientifically cleaner "
              "one and the one this battery takes. The true process is "
              "this volume's own object: the driven 6-ring (a = 0.32, "
              "b = 0.18) observed through the 4-symbol sensor s(i) = i "
              "mod 4, an HMM whose observed process has a known minimal "
              "realization. The exact joint-probability Hankel over "
              "64 x 64 (prefix, suffix) contexts of length 3 returns "
              "machine-exact rank 5 — the sensor's collisions (states 0 "
              "and 4 emit the same symbol, 1 and 5 likewise) cost the "
              "process one dimension against its 6 hidden states — and "
              "the rank is stable from window 3 to window 4. The entropy "
              "rate, computed by the exact forward filter over four "
              "hundred thousand steps, is 0.9559 nats per symbol with a "
              "Monte Carlo standard error of a few parts in a thousand. "
              "The models: a linear state-space RNN (h' = hA + xB, "
              "logits = hC + c, d = 16) trained by backpropagation "
              "through time, whose Hankel singular values and reductions "
              "are exact closed-form objects via the Gramian machinery; "
              "and a vanilla tanh RNN (d = 16), the classic recurrent "
              "model, measured empirically. Three seeds each, identical "
              "regime."),
        ("p", "The compression claim is confirmed with an honest "
              "refinement. The tanh RNN reaches a cross-entropy of 0.959 "
              "against the entropy floor of 0.9559 — essentially optimal "
              "prediction — from a state whose spectrum collapses from "
              "16 dimensions to 3 at the one percent tolerance (3.0 "
              "across seeds; 2.7 at five percent). The linear RNN reaches "
              "0.979 with a Gramian profile whose effective rank crosses "
              "the true rank 5 at the five percent tolerance (7.3 at one "
              "percent, 6.0 at two, 5.0 at five, 4.0 at ten). The "
              "learned transition spectra carry the chiral complex pair "
              "in all three linear seeds — the models learn the record, "
              "not a smoothed surrogate; they rediscover the arrow's "
              "spectral signature. But the task knee is not at the WFA "
              "rank: the cross-entropy curve flattens at order 3, the "
              "predictive (sufficient-statistic) dimension, matching the "
              "tanh model's 3-dimensional state and the sigma profile's "
              "own elbow (sigma_2 = 4.77 dropping to sigma_3 = 0.89). The "
              "linear realization rank overcounts the information "
              "dimension by the modes that carry the joint law but not "
              "predictive entropy."),
        ("p", "The machinery was certified before it was trusted, in the "
              "Vol IX discipline: the Gramian fixed-point solution agrees "
              "with the direct Lyapunov series; the balanced-transform "
              "certificate (the balanced controllability Gramian equals "
              "diag of the squared sigma) holds at 8e-16; and the exact "
              "error-system Hankel norms — computed from the composite "
              "system's Gramians, no truncation, no tail bounds — agree "
              "with a direct 30 x 30-block Hankel SVD to four digits on "
              "a random test system, with the boundary-order truncation "
              "hitting the AAK floor exactly. One mid-session transpose "
              "bug in the system convention (the model's row-vector "
              "dynamics against the column-vector Lyapunov equations) "
              "produced unstable reduced models and was caught by exactly "
              "these certificates; the numbers below are from the "
              "repaired, re-verified machinery."),
    ]},
    {"title": "Experiment 1 — the AAK extraction and the baselines", "blocks": [
        ("p", "The extraction is the square-root balanced truncation at "
              "orders 1, 2, 3, 4, 5, 6, 8, 10, 12, and 16, with the exact "
              "Hankel-norm error of every truncation computed from the "
              "error system. The AAK interval holds ten of ten: the "
              "measured error lies between the floor sigma_{n+1} and the "
              "tail sum at every order, as the theorem demands — the "
              "optimal rank-n Hankel approximant cannot beat sigma_{n+1} "
              "and the balanced truncation cannot beat the tail. The "
              "chat's prediction that 'the distortion-rate curve will "
              "match the predicted sigma_{n+1} lower bounds' is thus "
              "approximately true in the strongest honest sense available: "
              "the measured ratios of error to floor are 1.00 at the "
              "boundary orders n = 1 and 2, 1.00 again at the last "
              "surviving mode, and between 1.02 and 1.31 inside — the "
              "truncation is AAK-optimal exactly where the tail is "
              "negligible, and the profile shows both regimes. The exact "
              "curve-match is refuted, as different norms must disagree; "
              "the knee prediction is exact."),
        ("p", "The baseline adjudication splits honestly. Against random "
              "state deletion the AAK extraction wins at every order — "
              "1.11 to 1.48 against 0.98 to 1.38 on the cross-entropy "
              "scale — and against magnitude deletion it wins or ties "
              "essentially everywhere. But against direct retraining of "
              "an order-n model, the truncated big model loses at the "
              "lowest orders: at n = 1 the fresh small model reaches "
              "1.12 against 1.30, at n = 2 it reaches 1.04 against 1.38, "
              "and from n = 3 they tie at the parent model's level. The "
              "chat's claim that the AAK extraction 'outperforms existing "
              "distillation baselines at the same parameter count' is "
              "confirmed against the pruning baselines and refuted "
              "against matched-size direct retraining at the bottom "
              "orders: the truncated model inherits structure a tiny "
              "model cannot use, and retraining adapts. Figure 1(c) "
              "records the split. The deeper reading is the corpus's own: "
              "the sigma spectrum is a compression budget — the elbow at "
              "sigma_3 predicts the task knee exactly — but the budget "
              "counts the linear realization's modes, and the sufficient "
              "statistic is smaller than the realization."),
    ]},
    {"title": "Experiment 2 — the sensor-coarsening scan", "blocks": [
        ("p", "The chat's second experiment demands a POMDP benchmark "
              "with a restricted sensor; it names RockSample, Hallway, "
              "and 'a sensor-limited version of the Tiger problem,' and "
              "this battery takes the Tiger branch because it admits "
              "exact machinery at every coarsening. The canonical Tiger: "
              "hidden side, open-left or open-right for +10 correct or "
              "-100 wrong, listen at a cost of 1 with accuracy kappa. The "
              "listen channel is the sensor; coarsening it from 1.0 down "
              "to 0.5 is the scan. The solver is the finite-horizon "
              "(h = 8) alpha-vector backup with exact pruning — the "
              "upper-envelope monotone chain drops only never-maximal "
              "lines, so the value is exact at every belief — and the "
              "pruning itself returns the policy's belief regions and "
              "their kinks in linear time. The obstruction datum is the "
              "chat's 'finite-state policy fails' made exact: the gap "
              "between the optimal value and the best memoryless "
              "one-state controller, computed by enumerating all "
              "twenty-seven controllers and solving each closed chain. "
              "The register is the alpha-count. The curvature is the "
              "interior kink mass of the piecewise-linear value function, "
              "weighted and unweighted by the exact closed-loop belief "
              "visitation."),
        ("p", "The register law is the scan's headline. The optimal "
              "policy's alpha-count grows from 9 at kappa = 1.0 through "
              "59 at 0.95, 34 at 0.90, 44 at 0.80, 45 at 0.70 — and then "
              "explodes to 9153 at kappa = 0.60: the curse of history "
              "made visible in a single number. The poorer the sensor, "
              "the more belief regions the optimal controller must "
              "distinguish, until the game itself collapses to the stall "
              "regime (at kappa = 0.55 and 0.5 the optimal value is "
              "listen-out-the-horizon at -8, and the register collapses "
              "back to 280 and 4). This is Volume VIII's register "
              "inflation — there measured algebraically by the "
              "box-determinant law on the abelianized rung — measured "
              "here on the control side, exactly, on the chat's own "
              "benchmark. The obstruction iff holds at every kappa: "
              "o(kappa) > 0 exactly when the optimal policy needs "
              "memory, including the stall boundary where the optimum "
              "itself is memoryless and o = 0. The chat's weak form is "
              "verified at both ends: at kappa = 1 the obstruction "
              "vanishes and the one-state controller is optimal."),
        ("p", "The quantitative predictions fare worse, and the volume "
              "records the numbers rather than rounding them up. On the "
              "informative range (kappa at or above 0.7, where the game "
              "is not stall-dominated) the obstruction correlates with "
              "the oracle gap at Pearson r = 0.38 and the register at "
              "0.39 — weak; the chat's 'curvature predicts the magnitude "
              "of the gap' is refuted in its weighted form outright: the "
              "visit-weighted curvature anti-correlates at r = -0.95, "
              "because as the gap grows the closed-loop visitation "
              "concentrates on the flat listen-and-stall paths where the "
              "value function has no kinks. The raw interior kink mass "
              "saturates near its telescoping ceiling. What survives is "
              "the structure: the iff exact, the register inflation "
              "dramatic, and the finite-horizon stall identified as the "
              "honest confound — the memoryless controller's best coarse "
              "option is to avoid the catastrophe by never committing, "
              "which caps its loss and decouples the obstruction from "
              "the gap."),
        ("p", "The record side of the experiment returned a theorem "
              "instead of a curve, and it is worth stating as such: the "
              "Tiger's listen record is conditionally iid given the "
              "hidden side, so every block law is the exchangeable "
              "mixture one-half product of P(u_t given L) plus one-half "
              "product of P(u_t given R), which is invariant under index "
              "reversal — the arrow of the record is identically zero at "
              "every sensor quality, verified on all sixteen 4-blocks at "
              "every kappa to a maximum deviation of 3.5e-18. The chat's "
              "bridge from control performance to the arrow of time "
              "cannot be tested on memoryless-sensor benchmarks: the "
              "record stratum degenerates by construction. The bridge "
              "lives on sources with temporal structure — exactly the "
              "class Part 1's laundering theorems cover — and the "
              "experiment, honestly run, separates the strata it was "
              "meant to conflate."),
    ]},
    {"title": "Experiment 3 — the sheaf diagnostics", "blocks": [
        ("p", "The chat's third experiment constructs a cellular sheaf "
              "from a network's local computations and predicts that "
              "nonvanishing cohomology tracks training failures, with the "
              "harmonic norm correlating with the validation gap; its "
              "named benchmarks are SCAN and COGS for compositional "
              "generalization. The battery takes the compositional "
              "branch at its cleanest: modular addition on Z_7, (a, b) "
              "mapping to (a+b) mod 7, the minimal two-token-family "
              "compositional task, with a 2-64-64-7 ReLU MLP trained to "
              "convergence (twelve seeds per split) on four splits — the "
              "compositional quadrant split (train a and b in 0..3, "
              "sixteen pairs, thirty-three held out), an intermediate "
              "split (thirty-six and thirteen), the full-grid control, "
              "and a scattered random-60 split. The sheaf is the cellular "
              "sheaf on the bipartite token graph: fourteen token "
              "vertices (seven row, seven column), the training pairs as "
              "edges, vertex stalks the hidden activation space, and the "
              "edge restriction maps the per-token PCA projectors of that "
              "token's training activations. The diagnostic is the "
              "coboundary energy of the identity section: for each "
              "training edge, the normalized disagreement between the "
              "row-token and column-token reconstructions of the shared "
              "example's activation — the failure of the local "
              "representations to glue into a global section, the honest "
              "computable instantiation of the chat's harmonic norm."),
        ("p", "The compositional failure reproduces exactly as the "
              "literature reports it: training accuracy 1.000 on every "
              "split and every seed, while held-out accuracy is 0.073 on "
              "the compositional split, 0.006 on the intermediate, 0.000 "
              "on the scattered random-60, and 1.000 on the full control. "
              "The network memorizes its training pairs and fails to glue "
              "the token geometries — including the scattered split's "
              "held-out compositions of seen tokens, where both tokens "
              "have trained subspaces and the composition is the only "
              "new thing. The sheaf's verdict splits cleanly between "
              "task-level and seed-level, and the split is the "
              "experiment's honest result. Task-level: the mean "
              "coboundary energy orders the four splits exactly as their "
              "OOD errors do — 0.541 for the full control against zero "
              "OOD error, 0.577 for the compositional against 0.927, "
              "0.594 for the intermediate against 0.994, 0.615 for the "
              "random-60 against 1.000 — a perfect ordering. The energy "
              "predicts which task geometry fails."),
        ("p", "Seed-level: within a split, the correlation between the "
              "energy and the OOD error across the twelve seeds is null "
              "to slightly negative (-0.20 and -0.18 on the two "
              "informative splits, 0.0 where there is no variance to "
              "correlate). The pooled correlation of 0.59 is dominated by "
              "the split separation, and the volume flags it as such: "
              "the sheaf diagnostic is a geometry-of-the-task predictor, "
              "not a which-random-seed-fails predictor. The chat's claim "
              "'the harmonic norm correlates with the validation gap' is "
              "therefore confirmed at the task level and refuted at the "
              "seed level on this benchmark — the honest split that "
              "SCAN-scale experiments with single runs cannot even "
              "express, because they cannot separate the two variances. "
              "The edge-level diagnostic on the random-60's both-trained "
              "held-out pairs completes the picture: the "
              "token-reconstruction conflict on unseen compositions, "
              "measured per run, is the sheaf's local instrument, and its "
              "correlation with the per-run error is recorded in the "
              "results JSON at 0.0 — the local instrument sees the "
              "geometry, not the seed."),
    ]},
    {"title": "The ledger", "blocks": [
        ("p", "What survived this session: the four theorems of the "
              "classification (soundness verified to exhaustion, the "
              "rank-doubling law six of six with the closed-form "
              "mechanism, the one-way valve exact, and the "
              "reflection-laundering theorem discovered, proved, and "
              "tested against a designed counterexample); the "
              "scope-theorem answer to the ordered question — the "
              "equivalence holds exactly where the non-reversibility is "
              "spectrally carried, the abelian families with "
              "arrow-carrying observables, and the rank defect is the "
              "abelian shadow of the arrow; and the three experiments "
              "run at full audit strength with their predictions split "
              "honestly — the AAK interval exact and the knee exact, the "
              "register explosion measured, the sheaf ordering perfect at "
              "the task level. What was refuted: the chat's "
              "distortion-rate curve-match (approximately true, exactly "
              "false, ratios 1.00 to 1.31), its AAK-beats-retraining claim "
              "(reversed at the lowest orders), its curvature-predicts-"
              "the-gap claim (anti-correlated in the weighted form, "
              "confounded by the stall), and the seed-level form of the "
              "sheaf-correlation claim. What was discovered: the "
              "reflection-laundering theorem and the chirality reading of "
              "the ring's arrow; the exchangeability degeneracy of "
              "memoryless-sensor records; the predictive-dimension-versus-"
              "realization-rank gap in sequence-model compression; and "
              "the positive measure of the hidden-arrow quadrant."),
        ("p", "The corpus integration lands on three prior volumes. "
              "Volume VIII's abelianized rung is the algebraic home of "
              "the scope theorem: the circulant class where the transport "
              "sandwich closed is the same class where the arrow is a "
              "rank, and the register inflation it measured by the "
              "box-determinant law reappears here as the Tiger's "
              "alpha-count explosion under sensor coarsening — the same "
              "law measured on both sides of the observation boundary. "
              "Volume IX's exact-norm discipline is the machinery that "
              "made the AAK interval and the balanced-truncation "
              "certificates trustworthy, and the mid-session transpose "
              "bug that the certificates caught is the discipline "
              "working exactly as designed. Task 14's stratification "
              "record completes: the three strata are now separated by "
              "theorems rather than by slogans — the memory stratum (the "
              "Hankel rank, the BT2 side), the arrow stratum (the "
              "reversal divergence, the BT3 side, a chirality that "
              "sensors can launder exactly), and their meeting at the "
              "register, exact only on the abelian slice. 'It and bit "
              "from record' now has its sensor-theoretic content: the "
              "record is the pushforward, its arrow is bounded by the "
              "world's, and its rank is the abelian shadow the world "
              "casts when the world is abelian enough."),
        ("p", "The remaining open links are unchanged from Volume IX's "
              "ledger and are carried forward honestly: the cell's exact "
              "D(2) between the measured walls [1.000, 1.2771], with the "
              "rank-wall obstruction standing; Open 7.13, the "
              "non-commutative AAK construction, which the "
              "abelian-shadow theorem of this volume now frames "
              "precisely — the free-monoid approximants live beyond the "
              "abelian slice, exactly where the equivalence stops being "
              "structural; Phi's uniqueness; Risk 4; the bounded "
              "benchmarks; and the n = 4, L = 10 leg of the record-phase "
              "scan. The next natural link this session's mathematics "
              "opens: the reflection-laundering theorem for non-ring "
              "dynamics — which irreducible chains admit a reversal "
              "symmetry at all, and what the lattice of "
              "arrow-preserving sensors looks like off the circulant "
              "class — is stated as an open problem with the 3-ring's "
              "minimality (the identity is its only "
              "handedness-preserving sensor) as the first datum."),
        ("stats", [("4 + 1", "theorems proved or discovered this session "
                             "(T1-T4, the reflection-laundering theorem)"),
                   ("68.6%", "of B3 has a real spectrum with D > 0 — the "
                             "hidden-arrow quadrant's positive measure"),
                   ("9 → 9153", "the optimal Tiger controller's register "
                                "explosion as the sensor coarsens to 0.6")]),
    ]},
]
