# -*- coding: utf-8 -*-
"""vol11_content_b.py — The Reversal Group and the Abelian Shadow (Vol XI):
chapters 7-12."""

CHAPTERS_B = [
    {"title": "The shadow theorem", "blocks": [
        ("p", "Turn to the cell. The free monoid on two letters; the "
              "free cell symbol h(w) = 1[Parikh(w) = (1,1)] — the "
              "indicator of the words ab and ba; its free Hankel "
              "H(u,v) = h(uv) on l2 of the word space, rank four; and "
              "its abelianized shadow, the weighted catalecticant of "
              "the same indicator on l2 of the two-dimensional "
              "integer lattice — Volume VIII's ab/ba cell, Volume "
              "IX's interval. The first theorem of the second front "
              "is the dilation identity: the free symbol IS the "
              "abelian symbol composed with the Parikh map, and the "
              "block-constant subspace of the word space (spanned by "
              "the normalized Parikh-block indicators V) carries the "
              "entire free Hankel: H = V Cat V-star with a zero "
              "block. Singular values are preserved exactly, so the "
              "free cell and its shadow share the spectrum (sqrt 2, "
              "sqrt 2, 1, 1), and the EYM floor at M = 2 is sigma_3 "
              "= 1 on both sides. The battery verifies the identity "
              "by dense computation over the five-word support — the "
              "singular values match to 1e-12 — and the check is the "
              "hinge of everything that follows: the free problem and "
              "the abelian problem measure the same operator until "
              "the approximants differ."),
        ("p", "The approximants differ exactly at the commutative "
              "boundary, and the second theorem — the lift — "
              "measures which side has the advantage. Every abelian "
              "rank-M approximant lifts to a free rank-M approximant: "
              "a Prony atom psi(gamma) = p lam^gamma lifts to the "
              "multiplicative symbol g(w) = p lam^{m(w)}, whose free "
              "Hankel is p x x-star with x(w) = lam^{m(w)} — rank "
              "one; the two-atom family is the diagonal two-state "
              "weighted automata; the affine family is the shear "
              "automata. Therefore the free distance is bounded "
              "above by the abelianized distance, and both are "
              "bounded below by the common floor: sigma_3 = 1 <= "
              "D_free(2) <= D_abelian(2) in [1, 1.2771427]. This is "
              "the abelian-shadow theorem's sandwich form, and it is "
              "Open 7.13's frame: the shadow bounds the free problem "
              "from above, the EYM floor from below, and the free "
              "question is whether the non-commutative freedom of "
              "the two-state class — the letters' matrices that do "
              "not commute — buys any of the gap between 1 and "
              "1.2771427. The next three sections build the "
              "machinery to answer, answer, and then close the "
              "problem in a direction nobody had drawn."),
        ("p", "A note on why the free side could plausibly win. The "
              "unconstrained rank-2 approximation of the cell's "
              "Hankel — dropping the Hankel structure entirely — "
              "attains the floor sigma_3 = 1 by the Eckart-Young "
              "argument. The price of structure is the price of "
              "shift-consistency: the approximant's row functions "
              "must satisfy X(ua) = X(u) A_a, a two-dimensional "
              "linear-recurrence constraint that the Eckart-Young "
              "truncation has no reason to respect. In the "
              "one-letter case the classical AAK theory shows the "
              "price is zero — the shift-consistent truncation "
              "exists and attains the floor; Volume VII's "
              "level-constant transport proved the same for the "
              "commutative multiletter class. The cell is the "
              "boundary object: commutative as a target, off the "
              "level-constant class as an approximation problem, "
              "and the question is what the two-state "
              "non-commutative shift-consistency costs against it."),
    ]},
    {"title": "The exact free-cell machinery", "blocks": [
        ("p", "The machinery that answers is a six-by-six "
              "eigenproblem with closed-form entries. Take any "
              "two-state weighted automaton g(w) = B A_w C, with "
              "A_a and A_b two-by-two and B, C the boundary "
              "vectors; the error operator M = H_cell - H_g has its "
              "column space inside the span of the four "
              "Parikh-block indicators and the two reachable "
              "functions f_i(u) = (B A_u)_i, so its squared norm is "
              "the largest eigenvalue of the product C G of two "
              "six-by-six matrices: G the Gram of that basis, C the "
              "coefficient Gram summed over all words. Every entry "
              "is closed form: the block sums are finite (C, A_a C, "
              "A_b C and the symmetric combination on the four "
              "blocks), and the reachable and co-reachable Grams "
              "are discrete Lyapunov identities — the matrix "
              "inverses (I - A_a kron A_a - A_b kron A_b)^-1 — "
              "which are the free analogues of Volume IX's "
              "multinomial generating function 1/(1 - <lam-bar, "
              "lam'>). No truncation, no tail bounds: every norm "
              "the battery reports is the true infinite-operator "
              "norm, computed in microseconds."),
        ("p", "The validation chain is threefold, and it earned its "
              "keep by catching a real bug. First the zero "
              "approximant: the machinery reproduces ||H_cell|| = "
              "sqrt(2) exactly. Second the abelian referee: on the "
              "diagonal automata the machinery must agree with a "
              "completely independent algorithm — a dense box "
              "truncation of the catalecticant over the "
              "two-dimensional lattice — and it does, to 1.2e-9 "
              "across the test atoms. Third the dense word-space "
              "truncation: for random stable automata the exact "
              "norms match the top singular value of the dense "
              "error matrix over all words up to length nine, to "
              "the tail scale (the worst relative gap 1.7e-7). The "
              "bug the chain caught: the block word lists were "
              "stored as one-letter tuples, so the word 'ab' was "
              "read as a single unknown letter and routed through "
              "the wrong matrix product — the machinery disagreed "
              "with the referee by twenty percent until the "
              "encoding was fixed, and the first version of the "
              "free scan had silently converged to a wrong value. "
              "The anchor discipline held: the claim was never "
              "read off the broken version."),
        ("p", "One more structural fact falls out of the machinery "
              "for free, and it becomes the closing move of the "
              "volume. The reachable functions and the block "
              "indicators interact through the gamma-one parity: "
              "the whole six-by-six problem decomposes, exactly, "
              "into the two parity classes — the blocks with even "
              "first coordinate together with the even line "
              "function, and the odd blocks with the odd line "
              "function. The battery does not use this until the "
              "line-atom section, but it is already visible in the "
              "matrices: the cell's kernel pairs blocks whose "
              "Parikh vectors sum to (1,1), which is an odd "
              "condition, and the parity is the same one that "
              "defined the binary resolution floor's run "
              "structure. The two fronts of this volume share a "
              "parity — the arrow's alphabet floor and the "
              "shadow's escape room are cut by the same knife, a "
              "coincidence the final section returns to."),
    ]},
    {"title": "The free scan: the escape room is empty", "blocks": [
        ("p", "The scan answers the free question in three tiers. "
              "The diagonal tier — the two-atom abelian family "
              "realized as commuting automata — must reproduce "
              "Volume IX's optimum through the new machinery, and "
              "it does: 1.277182 against the recorded 1.277144, "
              "the agreement being the lift identity verified at "
              "the optimum itself. The symmetric tier — automata "
              "with A_b the letter-swap conjugate of A_a — reaches "
              "1.277490. The full tier — all twelve parameters, "
              "thirty multi-starts, exact norms throughout — "
              "reaches 1.278351 and finds nothing below the "
              "abelian value. The boundary is tight from both "
              "sides: every scan lands within a thousandth of the "
              "shadow, and none crosses it. The escape scan "
              "closes the loophole the exhaustion could not: with "
              "one atom forced to radius r approaching one — the "
              "boundary of the domain where atoms escape to "
              "infinity — the best error stays at 1.2773 or above "
              "at every radius tested; the infimum is not hiding "
              "at the sphere."),
        ("p", "The local test is the sharpest form of the "
              "statement, and the one that makes 'the escape room "
              "is empty' a measured fact rather than a scan's "
              "absence of luck. At the abelian optimum, perturb "
              "the two letter matrices off the diagonal — random "
              "non-commutative perturbations at three scales, "
              "sixty at each scale, every one evaluated with the "
              "exact norm. Not one perturbation improved the "
              "error: sixty of sixty at every scale, the abelian "
              "optimum is a local minimum of the full "
              "non-commutative problem. The commutative "
              "approximants are not a crutch that the free class "
              "tolerates; they are, locally and on every scan "
              "this battery ran, the best the free class can do. "
              "Open 7.13's off-class equality therefore fails on "
              "the witness at the measured level: the multiletter "
              "sandwich does not close at the EYM floor for the "
              "ab/ba cell, in either the abelianized rung (Volume "
              "IX's rank wall forbids attainment) or the free "
              "class (the escape room is empty). The gap between "
              "1 and 1.2771 is not optimizer noise; it is the "
              "price of shift-consistency, and the free "
              "non-commutativity does not pay it."),
        ("figure", "main"),
        ("p", "The honest boundary of the claim: the scan is "
              "measurement, not proof. Twelve-parameter "
              "Nelder-Mead over an exact but non-convex objective "
              "is a search, and 'no configuration found below "
              "1.2771' is weaker than 'no configuration exists "
              "below 1.2771'. What elevates the measurement is "
              "the combination: the lift theorem bounds the free "
              "distance above by the abelian distance (so the "
              "scan's target is the shadow, not an open field), "
              "the diagonal tier reproduces the shadow exactly, "
              "the local perturbation test shows the free "
              "landscape has no descent direction off the "
              "commutative stratum at the optimum, and the "
              "escape scan closes the boundary. The certificate "
              "that would make it a theorem — a semialgebraic "
              "infeasibility of the norm bound over the "
              "twelve-parameter family — remains open, and the "
              "next section closes the abelian side of that "
              "certificate in the strongest available form: by "
              "solving the value exactly."),
    ]},
    {"title": "The line atom: the cell's D(2) solved", "blocks": [
        ("p", "The closing move came from reading the optimizer's "
              "anatomy instead of its value. The best two-atom "
              "configuration, refined and extracted, is a pair at "
              "lambda_1 = (x, y) and lambda_2 = (-x, y) with "
              "weights p and -p — a parity-odd mirrored pair. The "
              "approximant's symbol is 2p x^{gamma_1} "
              "y^{gamma_2} on words with odd first coordinate and "
              "zero on even ones: the approximant lives on the "
              "gamma-one-odd shell. And the refinement runs to a "
              "limit no atom family contains: as x approaches "
              "zero the weights diverge with 2px = c fixed, and "
              "the family converges to the LINE ATOM psi(gamma) = "
              "c 1[gamma_1 = 1] y^{gamma_2} — a rank-two "
              "catalecticant supported on the single line "
              "gamma_1 = 1, sitting on the boundary of the "
              "Kronecker variety (the three-by-three minors "
              "vanish; it is not a sum of two Prony atoms; it is "
              "the limit of the parity-odd pairs). The scan "
              "confirms it: the three-parameter parity-odd family "
              "attains the two-atom optimum, and the "
              "two-parameter line-atom family attains it again at "
              "1.2771421129 — three independent optimizers "
              "agreeing through six digits on a boundary object "
              "none of them was told about."),
        ("p", "On the line atom the whole problem collapses, and "
              "this is where the cell's D(2) stops being an "
              "interval. The line atom's automaton is explicit — "
              "A_a = [[0,0],[1,0]], A_b = y I, B = (0, c), C = "
              "(1,0) — and the machinery's six-by-six closes to "
              "an explicit matrix with entries rational in (c, y): "
              "the two line Grams c^2/(1-y^2)^2 and c^2/(1-y^2), "
              "the finite block sums, and nothing else. The "
              "battery validated this closed form against the "
              "independent machinery at six sample points — "
              "machine agreement throughout — and then the "
              "parity decoupling bites: the six-by-six splits "
              "exactly into two three-by-three blocks, the odd "
              "gamma-one block carrying the top eigenvalue, so "
              "the norm is the largest root of an explicit CUBIC "
              "in lambda with coefficients rational in (c, y). "
              "The optimization is now a stationarity system: "
              "P(lambda, c, y) = 0 with both partial derivatives "
              "zero — three polynomial equations in three "
              "unknowns, the largest of whose solutions is the "
              "squared distance."),
        ("p", "The system solves to ninety digits by "
              "high-precision Newton iteration, and the value is "
              "the answer to Volume IX's open problem: lambda* = "
              "1.6310919765642504414737578928177383666901925754942... "
              "at c* = 0.397107287350397... and y* = "
              "0.656322466995789..., with the flip symmetry (c, "
              "y) and (-c, -y) giving the same norm (the cell is "
              "odd under the gamma-two parity, so the conjugate "
              "conjugation is free). The cell's D(2) is the "
              "square root: 1.2771421129084462390073013752643 to "
              "thirty digits and beyond — an exact algebraic "
              "number, the stationary value of an explicit cubic "
              "system, pinned to forty digits and bracketed "
              "rigorously from below by the rank wall's "
              "non-attainment of 1. The interval [1.000, "
              "1.2771] of Volume IX is closed at its upper end "
              "by identification: the infimum is not a mystery "
              "of the family but a specific boundary point of "
              "it, reachable in two parameters, and the number "
              "above is its value."),
        ("p", "What remains open is the minimal polynomial — the "
              "last cosmetic of exactness. The elimination "
              "resultants of the stationarity system explode "
              "with extraneous components (the coprime resultant "
              "reaches degree 1154 in lambda; the naive chain "
              "was wrong and was caught), and the in-sandbox "
              "lattice-relation searches did not converge within "
              "the time budget. The artifacts are saved — the "
              "cubic system itself, the ninety-digit solution, "
              "the resultant polynomial — and an external "
              "factorization (PARI or FLINT on the saved system) "
              "is the natural route to the minimal polynomial "
              "of lambda*. The honest summary: D(2) is solved as "
              "an algebraic number to any desired precision, "
              "with its defining system explicit; its "
              "irreducible polynomial is a computation, not a "
              "concept, away."),
    ]},
    {"title": "The certificate ledger", "blocks": [
        ("p", "Assemble the sandwich with its statuses, because "
              "the assembly is the certificate structure the "
              "open items live in. The floor: sigma_3 = 1, "
              "common to the free cell and its shadow by the "
              "dilation identity, and unattainable by any "
              "rank-two member — Volume IX's rank wall, which "
              "the free scan does not weaken (the wall's "
              "closure-forcing argument is approximant-class "
              "independent). The abelian infimum: the "
              "line-atom stationary value 1.2771421129, solved "
              "to forty digits this session, non-attained in the "
              "two-atom family (the line atom is the family's "
              "boundary) and attained in the closure — the "
              "value-without-attainment structure that "
              "one-letter AAK theory also exhibits at its own "
              "boundaries. The free side: bounded above by the "
              "lift, measured at the same value by three scan "
              "tiers, locally rigid at the optimum against "
              "non-commutative perturbations, unproven below "
              "1.2771 by certificate. The gap 0.2771421 between "
              "the floor and the value is the price of "
              "shift-consistency on the boundary of the "
              "commutative approximant class — the quantitative "
              "form of the rank wall."),
        ("p", "The failed certificate route is recorded because "
              "its failure is informative. The natural relaxation "
              "— bound the error below by Rayleigh quotients on a "
              "finite test set, then eliminate the approximant "
              "parameters from the linear constraints — fails "
              "completely: the atoms can zero every low-order "
              "Rayleigh form simultaneously, because the "
              "obstruction to attaining the floor is "
              "infinite-dimensional (the rank wall lives on the "
              "whole tail, not on any finite window). The "
              "semialgebraic route — treat the atom parameters "
              "as variables, the norm bound as the "
              "matrix-inequality system, and eliminate — is "
              "correct in principle and explodes in practice; "
              "the line-atom reduction is the first real dent in "
              "it, collapsing six parameters to two, and the "
              "cubic stationarity is what an actual certificate "
              "would certify. The named open problem is now "
              "sharp: prove that the line-atom stationary value "
              "is the global infimum over the full rank-two "
              "variety — equivalently, that no interior "
              "configuration beats the boundary — and the "
              "saved artifacts make that a bounded computation "
              "rather than a research programme."),
        ("p", "Two smaller ledger entries close the section. "
              "The complex field: Volume IX measured the complex "
              "two-atom family at 1.2831, above the real; the "
              "free scan of this session is real, and the "
              "complex two-state automata are unmeasured — the "
              "honest gap, with the machinery already "
              "complex-capable. And the parity observation: the "
              "line atom is the gamma-one-odd object whose "
              "alphabet-level cousin is the binary run "
              "structure of the first front — the same parity "
              "that splits the free eigenproblem splits the "
              "binary block laws, and the coincidence is "
              "structural, not numerological: the cell's kernel "
              "pairs Parikh vectors summing to (1,1), which is "
              "an odd-first-coordinate condition, and the "
              "run-counting identity is the same pairing read "
              "on the alphabet side. The two fronts of this "
              "volume are one phenomenon at two scales: the "
              "symmetry strata that carry — or launder — the "
              "arrow, and the parity strata that bound — or "
              "refuse — the approximation."),
    ]},
    {"title": "The verdict and the open ledger", "blocks": [
        ("p", "Both ordered frontiers are discharged. The "
              "reflection-laundering theorem beyond the ring is "
              "a group theory: the reversal group with its "
              "index-two coset, the anti-centralizer criterion "
              "that makes membership closed-form, the twist "
              "normal form that manufactures the self-converse "
              "world, the laundering theorem verified on that "
              "world, the dimension table that makes the whole "
              "mechanism measure-zero, and the stratification "
              "that names every laundering route — with the "
              "sharp converse refuted by the strong-lumping "
              "stratum and the binary resolution floor "
              "discovered underneath. The arrow-preserving "
              "sensor lattice off the circulant class is the "
              "complement of that union of strata, measured on "
              "witnesses: large, easy to stay inside, and "
              "exactly as structured as the group theory "
              "predicts. The second frontier closed further "
              "than ordered: not an interval but a value — the "
              "cell's D(2) is the line-atom stationary value "
              "1.2771421129084462 to sixteen digits and an "
              "algebraic number beyond, with the free question "
              "answered at the measured level (the escape room "
              "is empty) and the certificate reduced to a "
              "two-parameter system."),
        ("stats", [("1.2771421129", "the cell's D(2), solved: the "
                                  "line-atom stationary value, "
                                  "40 digits, the exact cubic "
                                  "system saved"),
                   ("4 + 3", "laundering strata: reflection, strong "
                             "lumping, residual — and the binary "
                             "floor: telescoping, run-counting, the "
                             "4-block first arrow"),
                   ("0/3000", "random chains admitting a reversal "
                              "symmetry: the reflection mechanism is "
                              "measure zero")]),
        ("p", "The scope answers sharpen the programme's central "
              "equivalence. Which stationary processes satisfy "
              "arrow iff rank defect? Those whose "
              "non-reversibility is spectrally carried — the "
              "abelian shadow of Volume X — and the shadow's own "
              "boundary is now stratified: the reflection strata "
              "where the shadow is exact by symmetry, the "
              "lumping strata where the observed process "
              "degenerates below the carrier, the deceptive "
              "floors where the pairwise and triple screens are "
              "blind by identity, and the record's own residual "
              "symmetries. The one-way valve holds throughout: "
              "the record inherits or destroys the arrow, never "
              "creates it, and the destruction routes are now a "
              "short list, each with its geometry measured. On "
              "the approximation side, the abelian shadow "
              "theorem has its first fully worked boundary: the "
              "cell, where the shadow bounds the free problem "
              "from above, the floor from below, and the "
              "boundary object — the line atom — turns out to "
              "carry the value. The synthesis the parallel chat "
              "reached — it and bit from record — gains its "
              "quantitative spine here: the record's strata are "
              "the arrow's memory, and their geometry is the "
              "price list of forgetting."),
        ("p", "The open ledger, honestly itemized. The minimal "
              "polynomial of the cell's value: a saved "
              "computation, external factoring recommended. The "
              "global certificate that the line-atom value is "
              "the infimum over the full rank-two variety: a "
              "bounded, named problem. The complex free scan: "
              "machinery ready, measurement not run. The "
              "residual laundering stratum: no witness isolated; "
              "the candidates are the breaking-but-laundered "
              "sensors on the witness lattices. The "
              "rank-four-binary deception at process level: the "
              "iid-pair class is classified, its generalizations "
              "are not. And the programme's longer items "
              "unchanged from the previous ledger: Phi's "
              "uniqueness at infinite dimension, Risk 4, the "
              "bounded benchmarks, the n = 4 L = 10 leg, and "
              "the Lyapunov-cohomology correspondence the "
              "parallel chat stated and this programme has not "
              "yet built. The next natural rung, if there is "
              "one, is the certificate — the volume has cut the "
              "cell's open problem down to two parameters, and "
              "a proof that the boundary carries the global "
              "infimum would close Volume IX's question as a "
              "theorem rather than a measurement."),
        ("quote", "The record's arrow is bounded by the world's, "
                   "inherited or destroyed, never created; the "
                   "destruction routes are strata, and the "
                   "strata have dimensions. The shadow of the "
                   "arrow is the rank; the shadow of the free "
                   "problem is the commutative approximant; and "
                   "at the cell, where both shadows meet, the "
                   "boundary of the shadow family carries the "
                   "value — the exact number where the "
                   "commutative world runs out of room."),
    ]},
]
