# -*- coding: utf-8 -*-
"""vol11_content_a.py — The Reversal Group and the Abelian Shadow (Vol XI):
chapters 1-6 + tables + figure. All statements anchored to the session's
verification batteries (reversal_group.py, free_cell.py, line_atom.py,
minpoly_cell2.py and their results JSONs)."""

FIGURES = {
    "main": ("/home/z/my-project/github_repos/master/download/figures/"
             "reversal_shadow.png",
             "Figure 1 — The two fronts of this volume, three panels. "
             "(a) The arrow-preserving sensor lattice on a manufactured "
             "non-circulant self-converse witness (N = 4, rho = (01)(23), "
             "D = 0.115): the observed block reversal KL under all fifteen "
             "sensors, log scale — the two rho-invariant sensors launder "
             "the arrow to machine zero at every block length (the "
             "laundering theorem beyond the ring), while the "
             "rho-breaking sensors keep a positive arrow. (b) The binary "
             "resolution floor of the arrow of time: a random 2+2 binary "
             "lump (hidden rank 4) has an exactly symmetric 2-block law "
             "(the telescoping identity) and an exactly symmetric 3-block "
             "law (the run-counting identity) — the first possible binary "
             "arrow is the 4-block, where the curve rises; any 3-state "
             "binary lump is reversible at every length (the "
             "singleton-routing theorem). (c) The shadow sandwich on the "
             "ab/ba cell: the EYM floor sigma_3 = 1 (never attained — the "
             "rank wall), the abelian optimum 1.2771427 carried by the "
             "parity-odd line-atom pair, and the free scans clustered "
             "above it — the escape room is empty, and the "
             "non-commutative perturbations never improve (60/60 at every "
             "scale)."),
}

TABLES = {
    "mandate": {
        "caption": "Table 1 — The order, itemized and answered: the two "
                   "frontiers named at the close of the previous ledger "
                   "(Task 15's remaining links), the theorem package or "
                   "construction that discharges each, its status, and "
                   "its verification in this session's batteries",
        "header": ["The ordered link", "The deliverable", "Status",
                   "Verification"],
        "ratios": [0.24, 0.36, 0.17, 0.23],
        "font": 7.3,
        "rows": [
            ["(1) The reflection-laundering theorem beyond the ring — "
             "which irreducible chains admit a reversal symmetry; the "
             "arrow-preserving sensor lattice off the circulant class",
             "The reversal group G-hat = Aut ~ R (index-2 normal coset "
             "structure; asymmetric chains have exactly one reversal "
             "symmetry, an involution); the anti-centralizer criterion "
             "R(P) = centralizer(S) intersect anti-centralizer(K); the "
             "twist normal form F_ij = F_{rho(j)rho(i)} with "
             "manufactured non-circulant witnesses; the laundering "
             "theorem verified beyond the ring; the exact dimension "
             "table (the strata are proper linear varieties, measure "
             "zero); the laundering stratification (reflection / strong "
             "lumping / residual) with the DS witness adjudicated; the "
             "binary resolution floor theorem package",
             "PROVED (the group laws, the criterion, the normal form, "
             "the laundering, the genericity, the binary identities) "
             "and WITNESSED (the sharp converse FALSE: the "
             "strong-lumping route)",
             "reversal_group.py: the ring's G-hat = D_N for N = 3..8; "
             "the criterion 120/120; pi-preservation 5.6e-17; the "
             "twist error 0.0 on four witnesses; the laundering zeros "
             "exact at n = 2..6; the dimension table by exact integer "
             "row reduction; 0/3000 random self-converse; the binary "
             "identities to 1.1e-16"],
            ["(2) Vol IX's still-open cell D(2) / Open 7.13 — now framed "
             "by the abelian-shadow theorem",
             "The shadow theorem: the dilation identity (sigma(free) = "
             "sigma(shadow) exactly) and the lift (D_free <= "
             "D_abelian): the sandwich 1 <= D_free(2) <= D_abelian(2); "
             "the exact free-cell machinery (the 6x6 closed-form "
             "eigenproblem with the Lyapunov identities); the free scan "
             "over the 2-state WFAs — the escape room is empty, so the "
             "off-class equality fails on the witness at the measured "
             "level; and the cell's D(2) SOLVED: the optimum is the "
             "line-atom boundary family, reduced to a 2-parameter "
             "cubic stationarity system solved to 40 digits",
             "SOLVED: D(2) = 1.2771421129... (the line-atom stationary "
             "value; six digits stable across three independent "
             "optimizers, then 50 digits by the algebraic solve); the "
             "free-side verdict MEASURED; the minimal polynomial left "
             "open with the artifacts saved",
             "free_cell.py: the machinery validated three ways (zero "
             "exact, abelian referee 1.2e-9, dense truncation 1.7e-7); "
             "the diagonal subscan reproduces the Vol IX optimum (the "
             "lift verified); line_atom.py: the closed 6x6 validated "
             "exact, the gamma_1-parity block decoupling, the cubic "
             "stationarity solved to 90 digits"],
        ],
    },
    "group": {
        "caption": "Table 2 — The reversal group: the structure facts and "
                   "the canonical examples. Aut(P) is the permutation "
                   "automorphism group; R(P) the reversal symmetries; "
                   "G-hat = Aut + R the reversal group",
        "header": ["Object", "Aut(P)", "R(P)", "G-hat", "The fact"],
        "ratios": [0.24, 0.13, 0.13, 0.13, 0.37],
        "font": 7.0,
        "rows": [
            ["The driven (a,b)-ring, N = 3..8", "Z_N (the rotations)",
             "the N reflections", "the dihedral D_N",
             "Vol X's 'the arrow is the chirality' is the coset "
             "statement R = D_N \\ Z_N; at equilibrium (a = b) P is "
             "symmetric and R = Aut (reversible iff R = Aut)"],
            ["The normal-form witnesses (N = 4, 4, 5, 6)", "trivial "
             "(asymmetric)", "exactly one involution rho", "Z_2",
             "the asymmetric chain has at most one reversal symmetry "
             "and it is an involution (rho^2 = id): the chirality is a "
             "single coin flip, verified on all four witnesses"],
            ["A generic chain (any N >= 3)", "generically trivial",
             "empty", "trivial",
             "the twist loci are proper linear strata (exact dimension "
             "table): the set of chains admitting ANY reversal "
             "symmetry is measure zero — 0 hits in 3000 random 4-state "
             "chains"],
            ["N = 2 chains", "S_2", "= Aut", "S_2",
             "every 2-state chain is reversible: the reversal group is "
             "degenerate; the arrow needs N >= 3 states"],
        ],
    },
    "strata": {
        "caption": "Table 3 — The laundering stratification: the routes by "
                   "which a sensor destroys the chain's arrow, their "
                   "geometric nature, and the session's witnesses. The "
                   "ambient is the chain space of dimension N(N-1)",
        "header": ["The stratum", "The mechanism", "The geometry",
                   "The witnesses"],
        "ratios": [0.20, 0.30, 0.22, 0.28],
        "font": 7.0,
        "rows": [
            ["Reflection", "the sensor is rho-invariant for a reversal "
             "symmetry rho in R(P): the reversed chain is the "
             "rho-conjugate and the sensor is rho-blind",
             "the twist loci L_rho: linear, codim 3 (N = 3, "
             "transpositions) up to codim 8-9 (N = 4, involutions); "
             "measure zero",
             "all four normal-form witnesses (the laundering exact at "
             "every block length); the iid-pair process (the phase "
             "symmetry IS the chain-level reversal symmetry rho = "
             "(AD)(BC))"],
            ["Strong lumping", "the Kemeny-Snell conditions: states in "
             "a block have identical block profiles, so the observed "
             "process degenerates to a lower-dimensional Markov chain, "
             "reversible when the lump is 2-state",
             "linear, codim = merged-profile count; the DOMINANT "
             "laundering stratum (codim 1 against codim 3 on 3-state "
             "chains)",
             "Vol X's doubly-stochastic hidden-arrow witness: R = "
             "emptyset (verified by exhaustive search over S_3), yet "
             "the sensor {0}|{1,2} launders completely — the sharp "
             "converse is FALSE; the constructed 4-state "
             "strong-lumping witness (D = 0.334, laundered)"],
            ["Residual", "a symmetry of the record with no chain-level "
             "counterpart: the observed process's own degeneracy",
             "algebraic, measure zero (predicted)",
             "no witness isolated this session (the breaking-but-"
             "laundered sensors found on the witness lattices are the "
             "candidates; the typing is left open)"],
        ],
    },
}

CHAPTERS_A = [
    {"title": "The mandate", "blocks": [
        ("p", "The previous ledger closed with two frontiers. Volume X "
              "had generalized the rank-defect theorem and discovered, "
              "in its battery's exact zeros, the reflection-laundering "
              "theorem: if a state-space symmetry conjugates a chain's "
              "dynamics to its own time reversal, every "
              "symmetry-invariant sensor launders the arrow exactly, "
              "and on the N-ring every reflection is such a symmetry — "
              "the ring's arrow is its chirality. What remained open "
              "was the theorem's life beyond the ring: which "
              "irreducible chains admit a reversal symmetry at all, "
              "what the symmetry structure is, and which sensors "
              "preserve the arrow off the circulant class. The second "
              "frontier was Volume IX's honest interval for the (1,1) "
              "cell — the sandwich distance D(2) bounded between the "
              "EYM floor 1 and the measured 1.2771427 — together with "
              "Open 7.13, the multiletter Hankel equality off the "
              "level-constant class, now framed by the abelian-shadow "
              "theorem: the rank defect is the abelian shadow of the "
              "arrow, and the abelianized rung is the shadow of the "
              "free problem."),
        ("p", "This volume discharges both. The first frontier becomes "
              "the reversal group: a two-coset extension of the "
              "automorphism group inside the symmetric group, with a "
              "computable criterion (the anti-centralizer form), a "
              "normal form that manufactures non-circulant witnesses "
              "at will, an exact dimension table that makes the whole "
              "reflection mechanism measure-zero, and a "
              "stratification of every laundering route — with "
              "Volume X's doubly-stochastic witness adjudicated: its "
              "laundering is not reflection at all, and the sharp "
              "converse is false. Along the way the battery "
              "discovered a theorem cluster nobody had ordered: the "
              "binary resolution floor, in which the 2-block and "
              "3-block laws of every stationary binary process are "
              "symmetric by identity, and the first possible binary "
              "arrow is the 4-block law. The second frontier becomes "
              "the shadow sandwich: an exact free-cell machinery with "
              "closed-form Grams, a free scan that shows the "
              "non-commutative 2-state class does not escape the "
              "abelian shadow, and then the unexpected closing move — "
              "the cell's optimum runs to the boundary of the "
              "approximant variety, the line-atom family, where the "
              "whole problem collapses to a two-parameter cubic "
              "stationarity system whose solution is the value of "
              "D(2) to forty digits."),
        ("table", "mandate"),
        ("p", "The standing honesty discipline applies throughout. "
              "Every number below is either computed exactly in this "
              "session's batteries (reversal_group.py, free_cell.py, "
              "line_atom.py, minpoly_cell2.py, each with a results "
              "JSON) or labelled with its precision. Three mid-session "
              "defects were caught by the anchor discipline and are "
              "recorded because they shaped the claims: a word-"
              "encoding bug (the block word lists stored one-letter "
              "tuples, so the word 'ab' was read as a single unknown "
              "letter) that made the free machinery disagree with a "
              "dense truncation referee until fixed; a witness-"
              "rounding bug that briefly destroyed the exactness of "
              "the laundering zeros; and an elimination-chain error in "
              "the minimal-polynomial computation (eliminating c "
              "before y) that produced a bivariate impostor. Each was "
              "exposed by an independent check, and the batteries "
              "were re-run clean before any claim was read off."),
    ]},
    {"title": "The reversal group", "blocks": [
        ("p", "Fix an irreducible stochastic matrix P with stationary "
              "distribution pi, its time reversal P-hat = Pi^-1 P^T "
              "Pi, the automorphism group Aut(P) of permutation "
              "conjugations, and the reversal symmetries R(P) = {rho : "
              "rho P rho^-1 = P-hat}. The first theorem is that these "
              "objects assemble into a group: pi-preservation comes "
              "free (every reversal symmetry preserves the stationary "
              "measure, verified to 5.6e-17 across the battery), the "
              "products close (R times R lands in Aut, Aut times R "
              "stays in R), and when R is nonempty the automorphism "
              "group is an index-2 normal subgroup of the reversal "
              "group G-hat = Aut + R, so that R is a single coset — "
              "rho_0 Aut = Aut rho_0 — and the square of every "
              "reversal symmetry is an automorphism. The corollary is "
              "the structure of chirality: if the chain is "
              "asymmetric (Aut trivial) and a reversal symmetry "
              "exists at all, it is unique and it is an involution. "
              "The handedness of an asymmetric driven chain is a "
              "single coin, not a family."),
        ("p", "The driven ring is the canonical example and the "
              "theorem's connection to Volume X. For the (a,b)-ring "
              "with a different from b, the automorphisms are exactly "
              "the rotations Z_N (the reflections conjugate the "
              "circulant to its transpose, which is the (b,a) ring — "
              "not itself unless a = b), and the reversal symmetries "
              "are exactly the N reflections: the reversal group is "
              "the dihedral group, and Volume X's slogan — the ring's "
              "arrow is its chirality — is now the coset statement R "
              "= D_N \\ Z_N. At equilibrium the ring is symmetric, "
              "Aut swallows the reflections, and R = Aut: the "
              "equivalence 'reversible if and only if R = Aut' is the "
              "group-theoretic restatement of detailed balance. The "
              "battery verifies the classification for N = 3 through "
              "8 exactly, and the normal-form witnesses of the next "
              "section realize the asymmetric corner: four "
              "non-circulant driven chains, each with Aut trivial and "
              "R a single involution."),
        ("table", "group"),
        ("p", "The group law is worth one more remark because it "
              "explains why the reflection mechanism feels so "
              "structured on the ring and so fragile off it. An "
              "index-2 normal subgroup is normal by counting alone: "
              "there is exactly one nontrivial coset, and every "
              "element outside it conjugates the subgroup to itself. "
              "The reversal symmetries therefore form a torsor for "
              "Aut — a homogeneous space of handedness flips — and "
              "the arrow, which is nonzero exactly when R is disjoint "
              "from Aut, is measured by the pair (G-hat, Aut) up to "
              "that torsor. On the ring the torsor is large and "
              "abelian (the rotations), which is why so many sensors "
              "launder there; on an asymmetric chain the torsor is a "
              "single point, which is why only the exactly "
              "rho-invariant sensors launder. The classification of "
              "which chains admit reversal symmetries is thus a "
              "classification of subgroups of S_N containing an "
              "index-2 copy of their own conjugation structure — a "
              "finite, computable problem, and the next two sections "
              "solve its computable and geometric halves."),
    ]},
    {"title": "The criterion and the normal form", "blocks": [
        ("p", "The computable half is the anti-centralizer criterion. "
              "Conjugate the dynamics by the square root of the "
              "stationary measure, A = Pi^(1/2) P Pi^(-1/2), and "
              "split it into its symmetric and skew parts S = (A + "
              "A^T)/2 and K = (A - A^T)/2. A permutation rho is a "
              "reversal symmetry if and only if it commutes with the "
              "symmetric part and anti-commutes with the skew part: "
              "R(P) = centralizer(S) intersect anti-centralizer(K), "
              "and Aut(P) = centralizer(S) intersect centralizer(K). "
              "The reading is physical: the reversible half of the "
              "dynamics must be invariant under the symmetry, and "
              "the irreversible half — the skew flux, the arrow's "
              "carrier — must be odd under it. A reversal symmetry "
              "is exactly a symmetry under which the arrow is odd; "
              "the battery verified the criterion against exhaustive "
              "search on 120 random chains with perfect agreement, "
              "for both R and Aut. The criterion makes every "
              "question of this section decidable by finite "
              "permutation search: given P, the whole reversal group "
              "is a closed-form computation."),
        ("p", "The geometric half is the twist normal form. Work in "
              "flux coordinates F = Pi P, so that the chain is the "
              "matrix of stationary flows with row and column sums "
              "equal to pi. Detailed balance is the symmetry "
              "F_ij = F_ji; the self-converse condition with "
              "symmetry rho is its twisted form F_ij = F_{rho(j) "
              "rho(i)} — the flux from i to j equals the flux from "
              "rho(j) to rho(i). The normal form follows: take any "
              "pi-flow G (rows and columns summing to pi, with rho "
              "preserving pi) and iota-symmetrize, F = (G + iota G)/2 "
              "where iota G is the twisted transpose: the result is a "
              "self-converse pi-flow whose chain is stochastic, "
              "irreducible, generically driven, and — crucially — not "
              "circulant. The battery manufactures four such "
              "witnesses (N = 4, 4, 5 and 6), each doubly stochastic, "
              "driven (D between 0.115 and 0.140), with the twist "
              "identity verified to 0.0 and the reversal group "
              "exactly the predicted single involution. The "
              "self-converse world is strictly larger than the "
              "circulant world, and its members are as easy to "
              "construct as a Sinkhorn projection: the "
              "reflection-laundering theorem finally has a home "
              "beyond the ring."),
        ("p", "The two halves combine into the classification "
              "answer. Which irreducible chains admit a reversal "
              "symmetry? Exactly those whose flux satisfies one of "
              "the finitely many twist systems F_ij = F_{rho(j) "
              "rho(i)}; the anti-centralizer criterion decides "
              "membership in closed form; and the normal form "
              "generates every member from an arbitrary flow. The "
              "honest scope note is that the flux twist is LINEAR: "
              "the self-converse chains form linear strata of the "
              "chain space, not a generic class — the subject of the "
              "genericity theorem two sections ahead, where the "
              "exact dimension table shows just how thin the strata "
              "are. But thin is not empty: within each stratum the "
              "arrow is real (the witnesses are driven), the "
              "laundering is exact, and the chirality is a single "
              "involution — the structure the ring taught us, "
              "transplanted into chains that no Fourier mode ever "
              "visits."),
    ]},
    {"title": "The laundering theorem beyond the ring", "blocks": [
        ("p", "The laundering theorem itself needed no repair, only "
              "a world to live in. Statement: if rho is a reversal "
              "symmetry of P and the sensor s satisfies s(rho i) = "
              "s(i), then the observed process is reversible — every "
              "block reversal KL is exactly zero. The proof is a "
              "pushforward: the chain conjugated by rho is a "
              "stationary Markov chain with transition rho P rho^-1 "
              "= P-hat, so the rho-image of the forward block law is "
              "the reversed block law; a rho-blind sensor cannot "
              "distinguish the image from the original, so the "
              "observed block law equals its own reversal. On the "
              "ring this was a fact about reflections; on the "
              "normal-form witnesses it is a fact about chains with "
              "no spectral symmetry whatsoever — the battery verifies "
              "it on all four witnesses, at block lengths two "
              "through six, with the invariant sensors at machine "
              "zero (the largest deviation across all witnesses and "
              "lengths is 2.8e-17)."),
        ("p", "The arrow-preserving sensor lattice off the circulant "
              "class is then a measurement, and Figure 1(a) shows it "
              "on the N = 4 witness with rho = (01)(23): fifteen "
              "sensors, two of them rho-invariant (the partitions "
              "that merge the orbit pairs), the rest breaking rho. "
              "The invariant two launder exactly. Of the thirteen "
              "breaking sensors, nine keep a strictly positive "
              "arrow — the observed block KL grows with the block "
              "length — and four launder despite breaking rho: they "
              "have wandered into the other strata of the "
              "laundering stratification, the strong-lumping "
              "conditions or the residual accidents, which the next "
              "section maps. The N = 5 witness tells the same story "
              "at scale (five invariant sensors of fifty-two, "
              "forty-three of the breaking sensors with positive "
              "arrow). The lattice is the honest answer to the "
              "ledger's question: off the circulant class, the "
              "arrow survives exactly the sensors that break every "
              "reversal symmetry AND miss the other laundering "
              "strata — the arrow-preserving sensors are the "
              "complement of a union of strata, and on the "
              "asymmetric witnesses that complement is large and "
              "easy to stay inside."),
        ("p", "One witness deserves its own paragraph because it "
              "closes a loop with Volume X's parallel chat. The "
              "iid-pair process — the binary process built from a "
              "four-state chain with one-way edges, whose pairs "
              "(0,1) and (1,0) are drawn independently at random "
              "phases — launders an infinite chain-level arrow (the "
              "one-way edges make the reversal divergence diverge) "
              "into a record with zero block KL at every length. "
              "The battery's first reading called this a residual "
              "accident, a symmetry of the record with no "
              "chain-level counterpart; the group theory corrected "
              "the reading: the chain's reversal group is nonempty "
              "(two symmetries), and the sensor IS invariant under "
              "rho = (AD)(BC) — the phase symmetry that looked like "
              "a property of the record is exactly the "
              "chain-level reversal symmetry. The laundering is the "
              "reflection route after all, and what made it look "
              "accidental is that the symmetry mixes the pair "
              "content with the phase. The correction is the "
              "theorem earning its keep: the group classifies the "
              "laundering, and the classification caught the "
              "battery's own first impression."),
    ]},
    {"title": "The genericity and the stratification", "blocks": [
        ("p", "How large is the self-converse world? The exact "
              "dimension table answers: for each permutation rho, "
              "the twist locus L_rho — the chains whose flux "
              "satisfies the rho-twist — is cut out by linear "
              "equations, and the battery computes the dimensions "
              "by exact integer row reduction in flux coordinates. "
              "On the 6-dimensional space of 3-state chains: the "
              "reversible locus (rho = identity) has dimension 5 "
              "(codimension 1), each transposition locus dimension "
              "4 (codimension 2), the 3-cycle loci dimension 2. On "
              "the 12-dimensional 4-state chains: the reversible "
              "locus codimension 3, the involution loci codimension "
              "4 to 5, the order-3 and order-4 loci thinner still. "
              "Every nontrivial locus is proper: the union over the "
              "finitely many rho is a measure-zero subset of the "
              "chain space, and the sampling confirms it — zero "
              "self-converse chains in three thousand random "
              "4-state draws. The reflection mechanism is the "
              "abelian world's mechanism: it lives on the "
              "circulant slice and its nearest relatives, and a "
              "generic chain's arrow cannot be laundered by "
              "reflection because there is nothing to reflect "
              "through."),
        ("table", "strata"),
        ("p", "The stratification sharpens the sharp converse. If a "
              "sensor launders the arrow, must the chain carry a "
              "reversal symmetry that the sensor respects? No: "
              "Volume X's doubly-stochastic hidden-arrow witness is "
              "adjudicated by exhaustive search — its reversal group "
              "is empty (all six permutations tested) — yet its "
              "sensor {0}|{1,2} launders completely, at every block "
              "length, to machine zero. The route is strong lumping: "
              "states one and two have identical block profiles "
              "(P_10 = P_20 = 1/5, exact in fractions), the "
              "Kemeny-Snell conditions hold, and the observed "
              "process IS the two-state chain [[.6,.4],[.2,.8]], "
              "which is reversible because every two-state chain "
              "is. The laundering stratification has three tiers: "
              "the reflection strata (linear, thin, the symmetric "
              "mechanism), the strong-lumping strata (linear, "
              "codimension equal to the merged-profile count — the "
              "DOMINANT mechanism, an order of magnitude thicker "
              "than reflection on three-state chains), and the "
              "residual strata (algebraic, measure zero, no "
              "witness isolated this session — the "
              "breaking-but-laundered sensors of the witness "
              "lattices are the candidates, left open). The one-way "
              "valve of Volume X is untouched: no stratum creates "
              "an arrow, every stratum only destroys it, and the "
              "destruction routes are now all named."),
    ]},
    {"title": "The binary resolution floor", "blocks": [
        ("p", "The battery's most unlooked-for discovery began as a "
              "debugging surprise: the two-block reversal KL of a "
              "binary observation refused to be positive no matter "
              "how driven the chain. The reason is an identity: for "
              "every stationary binary process, q(01) = q(10) "
              "exactly, because the pathwise difference of up- and "
              "down-transition counts is bounded by one while "
              "stationarity equalizes the rates — the telescoping "
              "identity, verified on four hundred random hidden "
              "Markov binaries to 1.1e-16. A pairwise arrow needs "
              "at least three symbols. And the surprise deepens at "
              "the next block: the 3-block law of every stationary "
              "binary process is also symmetric, by the "
              "run-counting identity — the reversal of a 3-block "
              "pattern is the same run-configuration (011 and 110 "
              "both count 1-runs of length at least two, 001 and "
              "100 both count 0-runs of length at least two, the "
              "rest are palindromes), so the run statistics that "
              "determine the block law determine it reversally "
              "too. The binary record cannot carry an arrow below "
              "the 4-block: the arrow's resolution has a floor "
              "built into the alphabet, not into the dynamics."),
        ("p", "What does the 4-block see? The adjacent run-pair "
              "order statistics — the rate of a 1-run of length a "
              "followed by a 0-run of length b, against the "
              "reverse. The binary process is reversible if and "
              "only if its run-length sequence is "
              "order-reversible. From there the singleton-block "
              "theorem closes the three-state world: if either "
              "block of the lump is a single state, the binary "
              "observation of ANY chain is reversible, because a "
              "singleton routes memorylessly — its exit "
              "distribution cannot carry the previous run — so the "
              "other block's entry sequence is iid and the "
              "observed process is an alternating renewal with "
              "iid runs. Every binary function of a 3-state chain "
              "is reversible (the forced 1+2 split), verified at "
              "every block length to 3.0e-17; the same holds for "
              "every 1+(N-1) split of every N, verified to "
              "3.3e-17. The first binary arrow needs both blocks "
              "of size at least two: hidden rank four with a 2+2 "
              "split, where the battery measures 99.8 percent of "
              "random instances carrying a positive 4-block arrow "
              "(maximum KL 0.0601), growing with the block length "
              "— Figure 1(b) shows the curve rising from exactly "
              "zero at n = 2 and n = 3."),
        ("p", "The floor is counted twice, and the two counts "
              "agree with Volume X's minimality. The pairwise "
              "arrow needs three symbols AND at least three "
              "states: the driven 3-ring's identity sensor is the "
              "minimal pairwise arrow carrier, and all three of "
              "its binary sensors are reflection-orbit sensors "
              "that launder — the ring's arrow survives only at "
              "full resolution. The block-pair arrow needs a "
              "2+2 binary lump: hidden rank four, both blocks "
              "non-singleton. Between them the floor explains, "
              "structurally rather than by reflection alone, why "
              "the 3-ring's non-identity sensors all launder: a "
              "three-state chain has no binary observation "
              "capable of an arrow at any block length, so the "
              "laundering of its binary sensors is forced before "
              "the group theory even enters. The minimal chiral "
              "record of Volume X is minimal in a stronger sense "
              "than stated there: it is the resolution floor of "
              "the arrow itself."),
    ]},
]
