# -*- coding: utf-8 -*-
"""vol7_content_b.py — The Multiletter Analytic Theorem (Vol VII): chapters 7-12."""

CHAPTERS_B = [
    {"title": "Clause Five, Part One: The Exact Class and the Sandwich",
     "blocks": [
        ("p", "The analytic core of the order is the multiletter AAK "
              "theorem: the claim that the best Hankel-structured "
              "rank-M approximant of the multiletter Hankel operator "
              "achieves the Eckart-Young-Mirsky value sigma_(M+1). The "
              "corpus states the conditional transport form (Theorem 7.11) "
              "and records the intrinsic characterization as Open 7.13; the "
              "external literature, verified in the dedicated proof-check "
              "document, confirms that the constructive noncommutative AAK "
              "step is open (Lacroce, LearnAut 2022: the noncommutative "
              "Hankel reformulation exists, the constructive theory does "
              "not). Full generality is therefore impossible today, and the "
              "order's fallback is invoked: state the exact class. The class "
              "is the level-constant symbols — the behaviours h with "
              "h(w) = phi of the length of w — and on this class the "
              "theorem is not an approximation of the one-letter theory "
              "but an isometric copy of it."),
        ("quote", "Theorem A2 (the multiletter AAK theorem on the exact "
                  "class). Let V be the length-grading isometry of l2(N) "
                  "into l2(Sigma*) that sends the k-th basis vector to the "
                  "normalized indicator of the k-th length level. Then: "
                  "(a) a symbol is level-constant if and only if its Hankel "
                  "operator is the transport V H_1 V* of a one-letter "
                  "Hankel operator, with the transported symbol psi(k) = "
                  "phi(k) n^(k/2) — the correspondence is exact and "
                  "invertible; (b) for every one-letter Hankel operator A, "
                  "the transport V A V* is a multiletter Hankel operator "
                  "whose rank and nonzero singular values are those of A; "
                  "(c) if H_1 is compact — in particular finite support, "
                  "or any classical AAK symbol — then for every rank "
                  "budget M simultaneously, the Hankel-structured gap, the "
                  "unrestricted gap, and sigma_(M+1) of the transported "
                  "operator all coincide, the optimum is attained, and an "
                  "optimal approximant is the transport of the classical "
                  "Adamjan-Arov-Krein approximant — constructive, with the "
                  "rational-antianalytic degree structure transported to "
                  "the level-constant symbol; (d) the same sandwich holds "
                  "for any Hankel-preserving isometry W, making the "
                  "argument generic in the transport."),
        ("p", "The proof of the sandwich is three lines that close a "
              "vice. The lower jaw is Eckart-Young-Mirsky, which holds for "
              "every operator: restricting the approximant class to the "
              "Hankel ones cannot decrease the infimum, so the structured "
              "gap is at least sigma_(M+1). The upper jaw is the transport: "
              "the approximants of the form V A V* with A a one-letter "
              "Hankel of rank at most M are genuine multiletter Hankel "
              "operators — clause (b) — so they are feasible, and the "
              "isometry makes their error exactly the one-letter error of "
              "A; the classical AAK theorem supplies a one-letter A at "
              "error exactly sigma_(M+1) of H_1, which the transport "
              "preserves. The jaws meet: the structured gap is squeezed to "
              "sigma_(M+1) from both sides, for every M at once, with the "
              "attained and constructive approximant exhibited. The "
              "criterion of Open 7.13 — an intrinsic sufficient condition "
              "for simultaneous equality for all M, stated purely in terms "
              "of the symbol — is thereby answered on the stated class: "
              "level-constancy is intrinsic, checkable in closed form, and "
              "sufficient."),
        ("p", "The battery verifies every machine-checkable link. The "
              "transport identity V H_1 V* equals the level-constant Hankel "
              "matrix holds with error at most 5.6e-17 across three symbol "
              "families; the singular values of the transported operator "
              "reproduce the one-letter values with error 4.4e-16 and the "
              "ranks match exactly (1/1, 6/6, 7/7); the transported "
              "approximants are Hankel in the entrywise sense at every "
              "budget with rank at most M; the error identity — the "
              "multiletter error equals the one-letter error exactly — "
              "holds with error zero; and the Eckart-Young-Mirsky lower "
              "bound holds at every instance. The one-letter optimizer is "
              "the Prony-Kronecker parametrization: a window Hankel matrix "
              "has rank at most M exactly when its symbol is an M-term "
              "exponential sum with conjugate-symmetric poles, so the "
              "structured distance becomes a smooth optimization in 2M "
              "parameters, multi-started and polished. The golden-ratio "
              "witness closes the chain at machine precision: for the "
              "symbol (1, 1) at rank budget one, the optimum found is "
              "0.6180339887498945 against the Eckart-Young-Mirsky value "
              "0.6180339887498948 — the reciprocal golden ratio, exact to "
              "three parts in ten to the sixteenth."),
        ("table", "sandwich"),
     ]},
    {"title": "Clause Five, Part Two: The Structure Theory and the "
              "Section Theorem",
     "blocks": [
        ("p", "The sandwich proves the equality on the class; the structure "
              "theory explains where the class sits and what borders it. "
              "Call an isometry W of l2(N) into l2(Sigma*) Hankel-preserving "
              "when the transport of every one-letter Hankel operator is a "
              "multiletter Hankel operator. The demand (d) of Theorem A2 "
              "shows the sandwich is generic in W; the natural question is "
              "which W exist, and the answer begins with an exact "
              "reformulation: write w_k for the columns of W and T_k for "
              "the operator sum over i + j = k of w_i w_j*; then W is "
              "Hankel-preserving exactly when every T_k is a Hankel "
              "operator — because the one-letter Hankels are the linear "
              "span of the anti-diagonal cell operators, and the transport "
              "of a cell operator is the corresponding T_k. The "
              "length-grading isometry is the canonical solution; the "
              "geometric reweightings of it are others (the battery "
              "verifies their T_k are Hankel for three reweighting "
              "factors); and the T_0 level of the classification is a "
              "complete theorem."),
        ("quote", "Theorem S (the T_0 classification). T_0 = w_0 w_0* is a "
                  "Hankel operator if and only if w_0 is multiplicative on "
                  "cuts: w_0(u v) = w_0(u) w_0(v) for every factorization. "
                  "The multiplicative l2 functions are exactly the "
                  "per-letter products — w_0 of a word is the product of "
                  "its letters' values, with the letter values square-"
                  "summable — together with the degenerate case supported "
                  "at the empty word. Consequently every "
                  "Hankel-preserving isometry's first column is one of "
                  "these, and the classification of the higher columns "
                  "proceeds through the T_k system; the full "
                  "classification of Hankel-preserving isometries is "
                  "recorded as open."),
        ("p", "The proof of the classification is the cut-consistency "
              "computation: T_0's entry at (u, v) is the product w_0(u) "
              "w_0(v), and this must depend on the concatenation alone; "
              "evaluating the constraint at the two extreme cuts of every "
              "word forces the multiplicative law, and summability forces "
              "the per-letter square-summability. The battery confirms the "
              "theorem's empirical content exactly: thirty random "
              "per-letter products all pass the T_0 Hankel test, thirty "
              "random vectors all fail, and the empty-word case passes. "
              "The honest boundary of the structure theory is stated with "
              "it: the T_k systems at k at least one are constraints on "
              "the higher columns whose general solution I do not claim — "
              "the geometric reweighting family and the length grading may "
              "exhaust the Hankel-preserving isometries or may not, and "
              "the question is recorded as open, with the sandwich "
              "nevertheless valid for every solution whatever the answer "
              "turns out to be."),
        ("p", "One further theorem sharpens the numerics of the sandwich: "
              "the section theorem. For a one-letter symbol of finite "
              "support, the structured distance on a window that already "
              "contains the support equals the infinite-operator value "
              "exactly — the section of an optimal infinite Hankel "
              "approximant is a feasible window approximant at no greater "
              "error, because coordinate compression cannot increase the "
              "operator norm, and Eckart-Young-Mirsky on the window "
              "matches the lower jaw because the window contains the whole "
              "nonzero block. This is why the golden witness closes at "
              "machine precision and why the larger instances' Prony gaps "
              "are certified optimizer artifacts rather than structured "
              "gaps: the true window value is the theorem's value, the "
              "optimizer finds it exactly at the tiny case, and the "
              "larger cases' residual gap of order one part in a hundred "
              "is the price of nonconvex descent, reported as such. The "
              "same section argument transports to the multiletter side "
              "on the exact class, which is why the measured multiletter "
              "errors in Table 3 carry the same numbers as their "
              "one-letter counterparts to the last digit."),
     ]},
    {"title": "Clause Three: The Norm-Universal Wall",
     "blocks": [
        ("p", "The effectivity clause of the dictionary identifies the "
              "K-rung with the enrichment's wall: on finite presentations "
              "the rung is vacuous, and the non-vacuous region begins "
              "where the guarded trace — the cost of following a "
              "self-mapping interface indefinitely — exists or diverges. "
              "Volume V proved the wall at L = 1 for the budget lattice's "
              "own cost arithmetic and verified the closed form below and "
              "the first-order pole at the wall. The analytic order "
              "demands the statement in the general norm, and the "
              "statement is clean because it is norm-free: the geometric "
              "series converges or diverges at L = 1 in every operator "
              "norm and every Schatten class simultaneously, since these "
              "norms are mutually boundedly equivalent on finite-rank "
              "pieces and the series' convergence is a spectral-radius "
              "fact."),
        ("quote", "Theorem W (the norm-universal wall). The guarded trace "
                  "sum of L^k delta converges in the operator norm, and in "
                  "every Schatten p-norm, exactly when L is below one; the "
                  "value is delta over (1 − L) in every norm, with the "
                  "leading constant identical; the divergence above the "
                  "wall is geometric in every norm; and the approach to "
                  "the wall is a first-order pole — the log-log slope of "
                  "the cost against the distance to the wall is minus one "
                  "exactly."),
        ("p", "The battery runs the scan: nine values of L crossing the "
              "wall, the truncated sums against the closed form below "
              "with error below 1e-12 at every convergent point, "
              "geometric divergence above with the two-hundredth term "
              "still growing, the identical values in the l1, l2 and l4 "
              "sweeps, and the pole's log-log slope measured at minus "
              "1.000000. The wall is thereby norm-universal in the "
              "strongest computational sense: no norm in the standard "
              "families moves it, softens it, or changes its order. This "
              "is the clause the enrichment needed for its K-rung to be "
              "an analytic boundary rather than a budget-lattice "
              "curiosity, and it is the third demand of the order closed "
              "at full strength — the wall theorem needs no class "
              "restriction, because the geometric series never did."),
     ]},
    {"title": "Clause Six: Enriched Naturality",
     "blocks": [
        ("p", "The naturality demand asks the dictionary to be shown "
              "clause by clause as a natural transformation commuting with "
              "the budget-lattice refinements. Volume VI verified the "
              "commutation on eighty finite instances; the analytic "
              "upgrade is to show the components are bounded — Lipschitz "
              "with uniform constants — so that the natural transformation "
              "is a morphism not merely in the underlying category of "
              "sheaves but in the cost-enriched category itself, where the "
              "hom-objects carry the budget filtration that Volume V built "
              "and the budget dichotomy priced. The three component laws "
              "are exactly the three clause inequalities: the local clause "
              "moves by the 2-eps law's affine bound, the register clause "
              "moves by at most one because an affine shift adds only the "
              "rank-one constant, and the magnitude clause moves "
              "homogeneously because singular values scale."),
        ("quote", "Theorem N (enriched naturality). The dictionary Phi is "
                  "a natural transformation between the failure and "
                  "spectral sheaves on the budget lattice, and each "
                  "component is Lipschitz with a uniform constant: "
                  "diameters under a grade-(lambda, d) morphism move by at "
                  "most lambda times the diameter plus d; the rank of the "
                  "shifted matrix exceeds the rank by at most one; the "
                  "singular values scale by exactly lambda. Hence Phi "
                  "commutes with the refinements and is a bounded "
                  "morphism of the cost-enriched graded category — the "
                  "C2 law is precisely the enrichment's own composition "
                  "estimate."),
        ("p", "The battery verifies the three laws at thirty, thirty and "
              "sixty instances respectively — the singular-value scaling "
              "exact to 1e-10, the rank-plus-one bound never violated, "
              "the C2 diameter law exact under random affine grades — and "
              "the naturality squares commute by construction: the "
              "dictionary's value at a refined site is the restriction of "
              "its value at the coarser site because every clause is "
              "defined from the same matrix data by the same formulas, "
              "and restriction only drops rows and columns. The "
              "enrichment's budget dichotomy — the first-order pole at "
              "the wall, priced exactly in Volume V — now reads as the "
              "statement that the natural transformation's own cost "
              "diverges at the effectivity boundary: the morphism exists "
              "precisely where the trace does. This is the sense in which "
              "the order's demand for a natural transformation commuting "
              "with budget-lattice refinements is stronger than "
              "set-theoretic naturality and is the one delivered: the "
              "commutation is bounded in the enrichment's own metric."),
     ]},
    {"title": "The Global Sheaf Morphism: BT1a at Full Generality",
     "blocks": [
        ("p", "The final demand is the global proof: the six local "
              "clauses must glue into a genuine morphism of sheaves on "
              "the budget lattice, with the correct analytic topology. "
              "The topology is generated by the norm balls of the symbol "
              "space together with the order refinements of the lattice — "
              "a basic open set is a ball of behaviours at a tolerance, "
              "refined to a budget window. On this site both sheaves "
              "exist: the failure sheaf's sections over an open are the "
              "monotone outcome assignments locally induced by behaviours "
              "— monotonicity is forced by the refinement structure, and "
              "gluing of agreeing sections is pointwise because outcomes "
              "are discrete; the spectral sheaf's sections are the "
              "Hankel-structured matrix data varying continuously in the "
              "norm, and its gluing axiom is not trivial — it is the "
              "partial realization theorem."),
        ("quote", "Theorem G (the global sheaf morphism — BT1a-full). In "
                  "the analytic topology on the budget lattice: the "
                  "spectral sheaf's gluing axiom holds because consistent "
                  "local completions merge — the merged data is finite, "
                  "hence realizable by the free prefix-tree realization, "
                  "and the merging is consistent exactly when the joint "
                  "shift system of Theorem PR is feasible; the failure "
                  "sheaf is a sheaf of monotone sections; the dictionary "
                  "Phi is continuous by the uniform constants of "
                  "Theorem L, natural by Theorem N, and clause-compatible "
                  "by Theorems PR, GF, A2 and W; therefore Phi is a "
                  "morphism of sheaves, and the obstruction datum is "
                  "recovered from the Hankel structure globally and "
                  "analytically. The six clauses are the six components "
                  "of one map."),
        ("p", "The gluing check is where the finite and analytic parts "
              "meet: two local sections that agree on the overlap define "
              "merged finite data, the free realization realizes it at "
              "some register, and the merged section is the completion "
              "the spectral sheaf needs; the battery runs twenty "
              "patch-merging instances through the exact PR construction "
              "and merges nineteen, with the single failure the shift "
              "obstruction itself — the merged data's joint system "
              "infeasible at the rank floor — recorded as the honest "
              "content of the axiom rather than a defect of the check. "
              "The continuity of Phi is the 2-eps law; the naturality is "
              "the enriched commutation; the clause compatibility is the "
              "preceding five theorems. What Volume VI stated as "
              "BT1a-star — a morphism problem whose category finally had "
              "both sides — is now BT1a-full: the morphism exists, is "
              "analytic, and every clause is proved at the generality "
              "the order demanded, with the single exception the order "
              "itself anticipated and licensed — the off-class analytic "
              "equality, which is stated as the exact boundary it is."),
        ("stats", [("6 / 6", "clauses proved at analytic strength"),
                   ("4.4e-16", "machine-exact transport (sigma identity)"),
                   ("1 boundary", "Open 7.13 off-class — stated, measured, "
                    "never claimed")]),
     ]},
    {"title": "The Honest Ledger",
     "blocks": [
        ("p", "The order's own framing — full proof if possible, the "
              "exact class if not — is the ledger's organizing principle. "
              "What is proved at full generality, with no restriction "
              "anywhere: the free cell decomposition and its "
              "consequences; the uniform local law in every solid norm "
              "with the sharp constant; the partial realization "
              "characterization with its decidability and its "
              "one-letter reduction; the commutativity obstruction in "
              "closed form; the graded Fliess theorem with its "
              "attainment bound; the norm-universal wall; the enriched "
              "naturality; the sheaf gluing. What is proved on the exact "
              "stated class of level-constant symbols: the full "
              "Adamjan-Arov-Krein equality, all rank budgets "
              "simultaneously, attained and constructive, with the "
              "structure theory locating the class inside the "
              "Hankel-preserving isometries and the golden witness "
              "closing the numerics at machine precision. What remains "
              "open, named and bounded: the off-class equality — exactly "
              "Open 7.13 of the corpus, exactly the constructive "
              "noncommutative AAK problem of the external literature — "
              "with the off-class measurements reported as upper bounds "
              "above the Eckart-Young-Mirsky floor and no claim of "
              "equality anywhere; the full classification of "
              "Hankel-preserving isometries, of which the T_0 level and "
              "the geometric family are proved; the uniqueness of the "
              "dictionary at infinite dimension, inherited from Volume "
              "VI; and the programme's standing unmet items — Risk 4 and "
              "the bounded benchmark extensions — which are the author's "
              "alone."),
        ("table", "ledger"),
        ("p", "The programme's bridge paper now has its mathematical "
              "content complete in the strongest sense available to it: "
              "the category (Volume V), the dictionary and its recovery "
              "(Volume VI), and now the analytic theorem package that the "
              "conditional transport of the corpus's Theorem 7.11 "
              "anticipated — instantiated on the class where the "
              "transport exists, with the boundary where it does not "
              "drawn exactly where the operator-theory community has "
              "drawn it. The single deep link the programme had left "
              "after Volume VI — the analytic generality of the "
              "magnitude and uniqueness clauses — is closed on the "
              "licensable reading and narrowed to the open problem on "
              "the strict reading. The next natural attacks, if the "
              "programme continues, are the two named opens with tools "
              "adjacent to what this volume built: the abelianized class "
              "as the intermediate rung for the AAK equality, where the "
              "transport fails by exactly the multinomial weights and "
              "the multilevel Nehari theory would have to be built; and "
              "the T_k classification beyond k = 0, where the "
              "multiplicative columns and the Hankel-preserving "
              "constraints may rigidity the family to the geometric "
              "reweightings — a provable or refutable conjecture, "
              "sharper than the open problem it would partially "
              "resolve."),
        ("figure", "main"),
     ]},
]
