# -*- coding: utf-8 -*-
"""vol9_content_b.py — The Sandwich Locus (Vol IX): chapters 7-12."""

CHAPTERS_B = [
    {"title": "The Locus Map: The Gap Valley Off the Rank-Two Locus",
     "blocks": [
        ("p", "The first-shell family — the corner coefficient, both axis "
              "coefficients, and the diagonal coupling c_ab at the (1,1) "
              "point — is the smallest family that leaves the rank-two "
              "locus: any live c_ab lifts the rank to three or four, and "
              "the closure question becomes genuinely open a priori. The "
              "battery maps it: two hundred eighty-five points over the "
              "(c_0, c_ab) plane at c_a = c_b = 1, each with the exact "
              "norm, the exact floor, and a multi-start optimizer over "
              "real atoms seeded with the amalgam's canonical answer. The "
              "map is a valley. The gap D(1) - sigma_2 is exactly zero on "
              "the slice c_ab = 0 — the amalgam theorem, measured at "
              "four parts in ten to the sixteenth — and strictly positive "
              "everywhere off it, growing smoothly with the distance from "
              "the slice: twenty-five parts per million at 0.03 off the "
              "slice, ten to the minus four at 0.11 off, nine thousandths "
              "at a quarter off, and up to 0.23 at the far corner."),
        ("p", "The high-precision spot checks protect the valley's reading "
              "from optimizer noise. Seven points were re-run with thirty "
              "real-atom and sixteen complex-atom starts each: the on-slice "
              "point closes at 4e-16, and every off-slice point retains a "
              "positive gap — the complex atoms never beat the real ones "
              "on these real symbols, and the gaps at the near-slice "
              "points persist at the scale of ten to the minus five. The "
              "map's single 'closed' grid point sits 0.03 from the slice "
              "with a gap of six parts per hundred million, inside "
              "optimizer tolerance of the valley floor but not on it. The "
              "honest reading, stated exactly: the closure locus at M = 1 "
              "on the first-shell plane is the amalgam slice; the gap "
              "field is strictly positive off it in every measured "
              "instance; the strictness is measured, not proved — no "
              "lower-bound argument beyond Eckart-Young-Mirsky is claimed "
              "off the slice, and the volume records that the sign-"
              "straddle criterion the session first derived is vacuous "
              "for self-adjoint operators, since the second singular value "
              "is by definition the second eigenvalue modulus and can "
              "never be straddled from both sides."),
        ("p", "The valley has structure worth naming. The gap's growth is "
              "asymmetric in the sign of c_ab and flattest along the "
              "negative-c_ab side near c_0 between a half and one; the "
              "slice itself is the floor for every c_0, negative corners "
              "included, because the amalgam theorem's convention covers "
              "them. What the valley measures is the price of the corner "
              "coupling: at rank three and above, the pinning that closed "
              "rank two exactly — one eigenvector annihilated, one "
              "aligned, one scale window — must now be delivered at two "
              "eigenvalues at once by a family with the same two shape "
              "parameters, and the battery says the family cannot pay "
              "except on the slice. The structural reason is the next "
              "chapter's descent argument, made precise at the cell, the "
              "family's most symmetric off-slice member."),
        ("table", "lens"),
     ]},
    {"title": "The Cell at M = 2: The Complete Family, the Rank Wall",
     "blocks": [
        ("p", "The (1,1) cell is the off-slice extreme — the symbol that "
              "is nothing but the diagonal coupling — and its M = 2 slot "
              "is the rung's standing open interval. Volume VIII bounded "
              "it as [1.000, 1.319] over a two-atom family measured with "
              "the tail-penalized surrogate. This volume re-measures it "
              "over the COMPLETE rank-two family with exact norms: the "
              "two-atom family and the affine family, real and — for the "
              "plain atoms — complex, with the complex affine family "
              "honestly excluded as outside the certified bilinear "
              "machinery's scope. The refined interval is [1.000, "
              "1.2771]: the best real two-atom approximant measures "
              "1.277144, the best real affine atom 1.277143 — the two "
              "families converge to the same value, which is itself "
              "evidence of a structural floor between them — and the "
              "correct complex two-atom search lands at 1.2831, no "
              "better."),
        ("p", "Why the floor is missed at M = 2 is now a structural "
              "statement, not a measurement. Closure would pin the error's "
              "top two singular values at one, and the pinning descent "
              "runs as follows: the plus-one eigen-directions force "
              "psi(1,1) = 1 and psi(2,0) = psi(0,2) = -1 with the "
              "anti-diagonal antisymmetry psi(beta + e_1) = -psi(beta + "
              "e_2) beyond; the pinned block at the (e_0, (2,0)) pair "
              "then forces psi(4,0) = 0 and its own vanishing couplings, "
              "which force psi to vanish at the (1,1) point it was just "
              "required to fill — the descent contradicts itself unless "
              "the approximant is the cell itself, which is rank four. "
              "The forced profile's finite part — the values at degrees "
              "zero through two that the pinning prescribes — has "
              "catalectic rank three, machine-measured, against the "
              "budget of two: the rank wall. No rank-two weighted "
              "catalectic satisfies the forced conditions; the interval "
              "is strict at least in the real self-adjoint case by the "
              "pinning argument, and the exact minimum over the "
              "exhaustive family remains open between the measured "
              "bounds."),
        ("quote", "The cell's M = 2 status, refined (first edition). "
                  "D(2) lies in [1.000, 1.2771]: the floor by "
                  "Eckart-Young-Mirsky, the ceiling by the complete "
                  "rank-two family searched with exact norms and "
                  "multi-start descent, real and complex. The "
                  "closure-forced profile has catalectic rank three "
                  "on its finite part — the rank wall — so no member of "
                  "the searched family attains the floor; the pinning "
                  "descent exhibits the contradiction explicitly. [The "
                  "second edition closes this interval at its upper "
                  "end: D(2) = sqrt(lambda*) exactly — the preface and "
                  "the strictness chain chapters below.]"),
        ("p", "The forced-profile scan confirms the wall from the "
              "constructive side: the two-atom antisymmetric candidates "
              "that satisfy the forced values at degrees one and two — "
              "built from the weight pairs (mu, -mu) that the "
              "antisymmetry dictates — have error norms from 9.9 to 44.8 "
              "against the cell, nowhere near the interval, because "
              "satisfying the pinning exactly at those degrees costs the "
              "family everything elsewhere. The optimizer's best "
              "approximants relax the pinning and pay 0.277 above the "
              "floor; the forced candidates keep it and pay ten to forty. "
              "The sandwich's fate on the cell is the gap between those "
              "two prices, and neither reaches zero."),
     ]},
    {"title": "What This Changes: The Boundary Restated",
     "blocks": [
        ("p", "For the corpus, the volume's changes are concentrated and "
              "explicit. The retraction removes Volume VIII's strict-"
              "failure witness and replaces it with a closure theorem; "
              "the budget narrative is corrected from obstruction to "
              "mechanism; the rank-one exhaustiveness stands unchanged; "
              "and the rung's version of the off-class boundary — which "
              "Volume VIII stated as the multinomial-weighted catalectic "
              "AAK problem with a witnessed strict failure — is restated "
              "as the locus: closed everywhere on the rank-two real "
              "locus by two identities and a criterion, open in measured "
              "gap off it, strictly open at the cell's second slot behind "
              "a rank wall. The boundary is no longer a single witness "
              "but a mapped field, and the map's floor is a theorem."),
        ("p", "The theorems connect outward as before. The amalgam closed "
              "form is an L-shaped instance of the general "
              "characteristic-identity mechanism — the product of the top "
              "two eigenvalue magnitudes equals the squared axis weight — "
              "and it is the first place in the programme where the "
              "multinomial weights, having been the obstruction all "
              "volume long, become the construction: the forced tail is "
              "what completes the equioscillation. The lens criterion is "
              "the rung's analogue of the Nehari all-pass condition, "
              "stated geometrically in the atom cone; the two-atom "
              "identity is the commutative shadow of the Adamjan-Arov-"
              "Krein equioscillation, certified where the free theory "
              "remains open. None of this touches the noncommutative "
              "problem: everything here lives behind the fibre isometry, "
              "in the abelianized image."),
        ("p", "For the framework's registers, two sharpenings replace "
              "Volume VIII's. The magnitude register — the singular tail "
              "— now carries the locus map: the gap field off the rank-"
              "two locus, vanishing exactly on it, with the valley's "
              "measured growth rates. The rank register carries the wall: "
              "the cell's forced profile at rank three against a budget "
              "of two, the first place in the programme where the "
              "resource clause — rank as the register — is the "
              "obstruction itself rather than the cost. Both "
              "sharpenings are machine-checked, and both are stated "
              "exactly where measurement replaces proof."),
     ]},
    {"title": "Volume VII's Ledger, Unchanged",
     "blocks": [
        ("p", "The order's third item asks for Volume VII's ledger "
              "reported unchanged: Open 7.13 and the benchmarks. The "
              "report is unchanged, and the volume's new results make the "
              "reason precise rather than merely negative. Open 7.13 "
              "asks for an intrinsic, symbol-level criterion for "
              "simultaneous equality at every rank budget — off the "
              "level-constant class, this is the constructive "
              "noncommutative Adamjan-Arov-Krein problem. Everything "
              "this volume closes is abelianized: the approximants are "
              "symbols on the Parikh lattice whose operators factor "
              "through the fibre isometry, and the free-monoid Hankel "
              "operators Open 7.13 concerns are not of that form. The "
              "rung's closures narrow the commutative side of the "
              "boundary; they do not build the noncommutative "
              "approximants; the ledger entry stands."),
        ("p", "The off-class measurements were re-verified fresh. Six new "
              "non-level-constant instances — random first-shell symbols "
              "outside every stated class — were run through the exact "
              "machinery: every one measures D(1) strictly above its "
              "floor, with gaps from three and a half thousandths to "
              "thirteen hundredths, the same regime as Volume VII's "
              "recorded gaps of two hundredths to fifty-five hundredths. "
              "The benchmark suite of Volume VII — the off-class "
              "instances, the bounded extensions, the n = 4, L = 10 leg "
              "— was not rerun this session and its entries are "
              "reproduced as recorded. The remaining named items keep "
              "their statuses: the dictionary's uniqueness at infinite "
              "dimension is inherited unchanged from Volume VI; Risk 4, "
              "the submission decision, remains the author's alone; the "
              "bounded benchmark extensions and the long leg remain "
              "unrun. One ledger line changed anywhere in the programme, "
              "and it changed in Volume VIII's, not Volume VII's: the "
              "amalgam witness entry, corrected by this volume's "
              "retraction."),
        ("table", "ledger"),
     ]},
    {"title": "The Honest Ledger",
     "blocks": [
        ("p", "The three tiers, stated as always. In the manuscripts "
              "already: the conditional transport of the corpus's "
              "Theorem 7.11, the classical one-letter theory, the "
              "multivariable Kronecker classification of finite-rank "
              "catalectics, and Volume VIII's box-determinant, atom, and "
              "budget results — all used, all cited. Newly proved: the "
              "amalgam closed form with its identities, its triple "
              "equioscillation, and the retraction it forces; the lens "
              "criterion on the rank-two real locus; the two-atom "
              "closure, proved modulo an identity certified in exact "
              "rational arithmetic at sampled points; and the cell's "
              "refined interval over the complete rank-two family, "
              "behind the measured rank wall. Measured and bounded, "
              "claimed as nothing more: the off-locus strictness in the "
              "gap valley; the affine closures; the complex amalgam "
              "closure; the complex two-atom gaps; the negative-corner "
              "closures. Open and named: Open 7.13 and the constructive "
              "noncommutative problem it embodies; the strict positivity "
              "off the rank-two locus; the cell's exact second-slot "
              "value; the complex generalization of the two-atom "
              "identity; and the standing programme items — the "
              "dictionary's uniqueness, Risk 4, the bounded benchmarks, "
              "the long leg."),
        ("p", "The shape of the answer to the order's second question is "
              "the volume's real deliverable, and it is worth one "
              "paragraph of summary. Which phi close the sandwich "
              "exactly? On the rung, at M = 1: all of the rank-two real "
              "locus — by the characteristic identity on the L-shapes, "
              "the critical-point identity on the two-atom family, "
              "measured closure on the affine points, the classical "
              "theory on the axes, and the double top on the crosses — "
              "and nothing else that the battery could measure, with the "
              "first-shell gap field vanishing exactly on the rank-two "
              "slice and positive at every off-slice point, and the "
              "cell's second slot strictly open behind the rank wall. "
              "The locus is a theorem on its floor and a measurement on "
              "its walls, and the volume distinguishes the two without "
              "blurring."),
        ("figure", "main"),
     ]},
    {"title": "The Next Links",
     "blocks": [
        ("p", "The programme's architecture is nine volumes deep, and the "
              "next links are named by what this volume left bounded. "
              "First, the strictness off the locus: a lower-bound "
              "argument for the first-shell gaps — the pinning descent "
              "made rigorous at rank three, where two eigenvalues must "
              "be pinned by one two-parameter family — would convert the "
              "valley's floor from measured to proved, and the descent's "
              "contradiction at the cell is the template. Second, the "
              "cell's exact D(2): the two rank-two families' common limit "
              "at 1.2771 suggests a third family or a certified bound "
              "closes the interval, and the rank wall says the answer, "
              "whatever it is, is not one. Third, the complex "
              "generalization: the amalgams close in the bilinear "
              "convention machine-exact, the complex two-atom targets "
              "measure small gaps, and the identity's complex form — "
              "if it exists — would finish the rank-two story in full "
              "generality. Fourth, the affine identity: the same "
              "certificate route over the differentiated Gram entries, "
              "eight measured closures waiting for their proof."),
        ("p", "And beyond the rung, the standing items keep their order: "
              "Open 7.13 and the constructive noncommutative "
              "Adamjan-Arov-Krein theory, where the external literature "
              "has drawn the boundary and the programme has mapped its "
              "commutative shadow ever more finely; the dictionary's "
              "uniqueness at infinite dimension; Risk 4; the bounded "
              "benchmarks; the n = 4, L = 10 leg. The volume ends as "
              "every one of them ends: with the proofs that exist, the "
              "measurements that bound what does not, one retraction "
              "delivered in full, and the names of the links that are "
              "next."),
        ("stats", [("4.4e-16", "the on-slice gap: the amalgam theorem "
                    "measured at the valley's floor"),
                   ("[1.000, 1.2771]", "the cell at M = 2, refined behind "
                    "the rank wall (3 > 2)"),
                   ("1 retraction", "Volume VIII's strict failure "
                    "withdrawn, artifact reproduced and diagnosed")]),
     ]},
]
